// AUTO-GENERATED by scripts/sync_extractors.mjs
// DO NOT EDIT — 2026-07-05 に index.ts から生成
// 再生成: node scripts/sync_extractors.mjs

// ── parseDurationToMonths ──
function parseDurationToMonths(text){
  if (!text || typeof text !== 'string') return null
  // <Nヶ月> / 【Nヶ月】 形式（S.H型: "<6ヶ月>"）の角括弧を除去して通常パターンで処理
  const t = text.trim().replace(/^[<【〈《「『](.+)[>】〉》」』]$/, '$1')
  let months = 0
  const yearMatch = t.match(/(\d+)\s*年/)
  const monthMatch = t.match(/(\d+)\s*[ヶかカ]月/)
  if (yearMatch) {
    const y = parseInt(yearMatch[1])
    // 50年超は西暦年（例: 2020年）の誤マッチとして無視
    if (y > 50) return null
    months += y * 12
  }
  if (monthMatch) months += parseInt(monthMatch[1])
  if (months > 0) return months
  // 漢数字・書き言葉の月数対応（O.Y型: 「六ヶ月」「一年九ヶ月」「二年六ヶ月」）
  const KANJI_NUM= {
    '零': 0, '一': 1, '二': 2, '三': 3, '四': 4, '五': 5, '六': 6,
    '七': 7, '八': 8, '九': 9, '十': 10, '十一': 11, '十二': 12,
  }
  const kanjiYear = t.match(/([一二三四五六七八九十]+)\s*年/)
  const kanjiMonth = t.match(/([一二三四五六七八九十]+)\s*[ヶかカ]月/)
  if (kanjiYear && KANJI_NUM[kanjiYear[1]] !== undefined) months += KANJI_NUM[kanjiYear[1]] * 12
  if (kanjiMonth && KANJI_NUM[kanjiMonth[1]] !== undefined) months += KANJI_NUM[kanjiMonth[1]]
  return months > 0 ? months : null
}

// ── excelSerialToDateStr ──
function excelSerialToDateStr(s){
  const n = parseInt(s)
  // 36526〜50000 = 2000年〜2036年の範囲のみ変換（誤認識防止）
  if (isNaN(n) || n < 36526 || n > 50000) return s
  const d = new Date(Date.UTC(1899, 11, 30) + n * 86400000)
  return `${d.getUTCFullYear()}/${d.getUTCMonth() + 1}`
}

// ── calcMonthsFromMultilineCell ──
function calcMonthsFromMultilineCell(cellValue){
  const parts = cellValue.split(/[\r\n]+/).map(s => s.trim())
    .filter(s => s && !/^[～~〜\-－]$/.test(s) && s !== '現在' && s !== '継続中')
  if (parts.length < 2) return null
  return calcMonthsFromDates(parts[0], parts[parts.length - 1])
}

// ── calcMonthsFromDates ──
function calcMonthsFromDates(start, end){
  const parseYM = (s) => {
    // 元号プレフィックス（g=Gregorian表記・昭和/平成/令和アルファベット）を除去
    const cleaned = s.trim().replace(/^[gGhHrRsS]/, '')
    const normalized = excelSerialToDateStr(cleaned)
    // "/" "-" "年" に加えて "." も区切り文字として許容（例: "1991.10"）
    const m = normalized.match(/(\d{2,4})[\/\-年.](\d{1,2})/)
    if (m) {
      let year = parseInt(m[1])
      if (year < 100) year = year < 50 ? 2000 + year : 1900 + year
      if (year >= 1970 && year <= 2100) return { year, month: parseInt(m[2]) }
    }
    // US 日付形式 M/D/YY or M/D/YYYY（Excel が日付セルを M/D/YY で出力するケース）
    const usm = normalized.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/)
    if (usm) {
      const month = parseInt(usm[1])
      let year = parseInt(usm[3])
      if (year < 100) year = year < 50 ? 2000 + year : 1900 + year
      if (month >= 1 && month <= 12 && year >= 1970 && year <= 2100) return { year, month }
    }
    return null
  }
  const s = parseYM(start)
  const e = parseYM(end)
  if (!s || !e) return null
  const months = (e.year - s.year) * 12 + (e.month - s.month) + 1
  return months > 0 ? months : null
}

// ── filterSkillYears ──
function filterSkillYears(sy){
  // スキル名として不適切なヘッダーラベル・金額・業務語をフィルター
  // 例: 「言語／FW」「OS／MW」「概要」「105万」等
  const NON_SKILL_RE = /^(?:言語[/／・]?(?:FW|ツール|DB|技術|OS)?|OS[/／・]?M?W?|DB[/／・]?(?:DC|OS|MW)?|FW(?:[/／・]ツール)?|ライブラリ|クラウド(?:[/／・]NW)?|ツール(?:[/／・]技術)?|MW(?:[/／・]DB)?|NW(?:[/／・]クラウド)?|概要|今年度|業務経験(?:年数)?|業種|工程|フェーズ|役割|開発規模|使用言語|使用技術|技術スタック|開発環境|言語[・]FW|言語[/]技術|技術[/]環境)$/
  const MONEY_RE = /\d+万(?:円)?|円$/
  // 個人情報・履歴ラベルをスキル名として誤抽出しないためのブロックリスト
  const PERSONAL_INFO_RE = /^(学歴|最終学歴|氏名|ふりがな|フリガナ|生年月日|年齢|性別|住所|国籍|最寄[駅]?|電話|メール|資格|自己PR|PR|所属|経験年数|合計|総計|計|小計|期間合計|担当工程|在籍期間|参画期間|携わ)$/
  // 日付・期間範囲がキーになっている場合を除外（例: "2022/2～2022/9", "2019年〜現在"）
  const DATE_RANGE_RE = /\d{4}[\/年]\d{1,2}/
  const result= {}
  for (const [k, v] of Object.entries(sy)) {
    if (k.startsWith('_')) { result[k] = v; continue }
    if (k.length > 30) continue
    // 純粋な数字（行番号・案件番号等）はスキルとして無効
    if (/^\d+$/.test(k.trim())) continue
    const kNoSpace = k.replace(/[　 ]/g, '')
    if (NON_SKILL_RE.test(kNoSpace)) continue
    if (MONEY_RE.test(k)) continue
    if (PERSONAL_INFO_RE.test(kNoSpace)) continue
    if (DATE_RANGE_RE.test(k)) continue
    result[k] = v
  }
  return result
}

// ── extractSkillYearsFromBodyText ──
function extractSkillYearsFromBodyText(text){
  const result= {}

  // 全角数字を半角に変換して年数を月数へ
  const parseYearsToMonths = (s)=> {
    const m = s.match(/([0-9０-９]+)年/)
    if (!m) return null
    const n = parseInt(m[1].replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFF10 + 0x30)), 10)
    return isNaN(n) || n < 1 || n > 40 ? null : n * 12
  }

  // 括弧内の補足・ラベルプレフィックスを除去してスキル名だけ返す
  // 「PHP(Laravel)」→「PHP」 / 「アピールポイント: PHP」→「PHP」
  const cleanSkillName = (s)=> {
    let r = s.replace(/\s*[（(][^）)]*[）)]/g, '').replace(/[・、,，\s　]+$/, '').trim()
    // コロン・全角コロンがある場合は最後のコロン以降を取る
    const colonIdx = Math.max(r.lastIndexOf('：'), r.lastIndexOf(':'))
    if (colonIdx >= 0) r = r.slice(colonIdx + 1).trim()
    return r
  }

  // スキル名として不適切な語句（除外リスト）
  const isNonSkill = (name)=> {
    if (name.length < 2 || name.length > 30) return true
    return /経験|以上|程度|開発|業務|システム|設計|構築|基盤|インフラ|サービス|アプリ|エンジニア|実務|案件|プロジェクト|当社|弊社|担当|スキル/.test(name)
  }

  // パターン1: 「スキル1、スキル2の経験がそれぞれN年以上」（複数スキル・同一年数）
  const patternEach = /([^\n。]{2,80})の経験がそれぞれ([0-9０-９]+年)/g
  let m
  while ((m = patternEach.exec(text)) !== null) {
    const months = parseYearsToMonths(m[2])
    if (!months) continue
    const skills = m[1].split(/[、,，・とやおよび及び]/)
    for (const raw of skills) {
      const name = cleanSkillName(raw)
      if (!isNonSkill(name)) {
        result[name] = Math.max(result[name] ?? 0, months)
      }
    }
  }

  // パターン2: 「スキルの経験がN年以上」（単一スキル。それぞれ除外）
  const patternSingle = /([^\s　、,，・（(）)\n]{2,20})の経験が(?!それぞれ)([0-9０-９]+年)/g
  while ((m = patternSingle.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const months = parseYearsToMonths(m[2])
    if (months && !isNonSkill(name)) {
      result[name] = Math.max(result[name] ?? 0, months)
    }
  }

  // パターン3: 「スキル：N年」「スキル（N年）」「スキル（約N年）」（明示的なコロン・括弧区切り必須）
  // 「スキル 年」のようなスペース区切りは日付と誤爆しやすいため除外
  // 約・おおよそ等のプレフィックスも対応
  const patternLabel = /([A-Za-z][A-Za-z0-9+#. _/-]{0,19}|[ァ-ヶー]{2,15}|[一-龯々]{2,10})\s*[：:（(]\s*約?\s*([0-9０-９]+年[0-9０-９]*[ヶかカ]?月?)/g
  while ((m = patternLabel.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const months = parseYearsToMonths(m[2])
    if (months && !isNonSkill(name) && !(name in result)) {
      // パターン3は1,2で取得済みのキーには上書きしない
      result[name] = months
    }
  }

  // パターン3b: 「スキル（Nヶ月）」（月数のみ・年なし）
  // 例: Java(2年2ヶ月) は pattern3 で捕捉済み、Springboot(6ヶ月) はこちら
  const patternMonthsOnly = /([A-Za-z][A-Za-z0-9+#. _/-]{0,19}|[ァ-ヶー]{2,15})\s*[（(]\s*([0-9０-９]+)[ヶかカ]月\s*[）)]/g
  while ((m = patternMonthsOnly.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const mo = parseInt(m[2].replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFF10 + 0x30)), 10)
    if (!isNaN(mo) && mo >= 1 && mo <= 360 && !isNonSkill(name) && !(name in result)) {
      result[name] = mo
    }
  }

  // パターン3c: 「スキル歴N年」「スキル歴N年以上」
  // 例: Laravel歴7年以上、Java歴10年
  const patternRekiYear = /([A-Za-z][A-Za-z0-9+#. _/-]{1,19}|[ァ-ヶー]{2,15}|[一-龯々]{2,10})歴\s*([0-9０-９]+)\s*年/g
  while ((m = patternRekiYear.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const yrs = parseInt(m[2].replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFF10 + 0x30)), 10)
    if (!isNaN(yrs) && yrs >= 1 && yrs <= 40 && !isNonSkill(name) && !(name in result)) {
      result[name] = yrs * 12
    }
  }

  // パターン3d: 【スキル】セクション後のスラッシュ区切り「Java(約15年以上) / Kotlin(約8年)」
  // 行内のスラッシュで区切られた「スキル名(約?N年)」形式を一括抽出
  const slashSkillSection = text.match(/(?:【スキル】|スキル[：:]\n?)([^\n]{10,300})/)
  if (slashSkillSection) {
    const sectionLine = slashSkillSection[1]
    const slashParts = sectionLine.split(/\s*[/／]\s*/)
    for (const part of slashParts) {
      const pm = part.trim().match(/^([A-Za-z][A-Za-z0-9+#. _-]{0,19}|[ァ-ヶー]{2,15})\s*[（(]\s*約?\s*([0-9０-９]+)\s*年/)
      if (pm) {
        const name = cleanSkillName(pm[1])
        const yrs = parseInt(pm[2].replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFF10 + 0x30)), 10)
        if (!isNaN(yrs) && yrs >= 1 && yrs <= 40 && !isNonSkill(name)) {
          result[name] = Math.max(result[name] ?? 0, yrs * 12)
        }
      }
    }
  }

  // パターン4: Word文書の箇条書き形式「● Java　5年」「・Python　3年」「▪ AWS　2年」
  // 行頭に箇条書き記号 + スキル名 + スペース/タブ + N年  （コロン・括弧なし）
  // スペース区切り誤爆を防ぐため行頭記号必須とする
  const patternBullet = /^[●•・▪▶◆■○◇►➤※→]\s*([A-Za-z][A-Za-z0-9+#. _/-]{0,29}|[ァ-ヶー]{2,15}|[一-龯々]{2,10}(?:[　 ][A-Za-z0-9+#.]{1,15})?)\s*[　 \t]+([0-9０-９]+年(?:[0-9０-９]+[ヶかカ]?月?)?)/gm
  while ((m = patternBullet.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const months = parseYearsToMonths(m[2])
    if (months && !isNonSkill(name) && !(name in result)) {
      result[name] = months
    }
  }

  // パターン5: 「スキル名　N年」行（行末が年数・タブ/全角スペース区切り）
  // Word職務経歴書の表形式テキスト化で見られる「Java\t5年」「Python　3年以上」
  // 誤爆防止: 行頭がスキル名のみ（先行テキストなし）かつ後続に余分なテキストがない行に限定
  const patternTabYear = /^([A-Za-z][A-Za-z0-9+#. _/()-]{1,29}|[ァ-ヶー]{2,15})\t([0-9０-９]+年[0-9０-９]*[ヶかカ]?月?(?:以上|程度|超)?)\s*$/gm
  while ((m = patternTabYear.exec(text)) !== null) {
    const name = cleanSkillName(m[1])
    const months = parseYearsToMonths(m[2])
    if (months && !isNonSkill(name) && !(name in result)) {
      result[name] = months
    }
  }

  // パターン6: 総経験年数ラベル（「経験年数：N年」「IT経験：N年以上」「経験N年」）
  // → スキルと対応しないため _totalProjectMonths に収める
  const patternTotalExp = /(?:経験年数|IT経験|総経験|開発経験)[：:]\s*([0-9０-９]+)\s*年/g
  while ((m = patternTotalExp.exec(text)) !== null) {
    const yrs = parseInt(m[1].replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFF10 + 0x30)), 10)
    if (!isNaN(yrs) && yrs >= 1 && yrs <= 50 && !result['_totalProjectMonths']) {
      result['_totalProjectMonths'] = yrs * 12
    }
  }

  // パターン7: 「参画期間: YYYY年M月 〜 YYYY年M月」+ 近傍の「使用技術: スキル1/スキル2」
  // Word職務経歴書のプレーンテキスト形式（表なし）に対応
  // 行単位で「参画期間」ラベル + 日付範囲を探し、前後10行の「使用技術」行からスキルを取得
  {
    const lines = text.split(/\n/)
    const nowYM = new Date().getFullYear() * 12 + new Date().getMonth() + 1
    const parseYMBody = (s)=> {
      const m3 = s.match(/(\d{4})年(\d{1,2})月/)
      if (m3) return parseInt(m3[1]) * 12 + parseInt(m3[2])
      const m4 = s.match(/(\d{4})[\/\-.](\d{1,2})/)
      if (m4) return parseInt(m4[1]) * 12 + parseInt(m4[2])
      if (/現在|今|継続|在籍中/i.test(s)) return nowYM
      return null
    }
    const PERIOD_LABEL = /^(参画期間|在籍期間|稼働期間|作業期間|プロジェクト期間|PJ期間|期間)[：:]/
    const SKILL_LABEL = /^(使用技術|使用言語|技術スタック|技術環境|開発環境|使用環境|言語|環境|スキル)[・・（(]?[^：:]*[：:]\s*(.+)/
    for (let li = 0; li < lines.length; li++) {
      const line = lines[li].trim()
      if (!PERIOD_LABEL.test(line)) continue
      // 期間を解析
      const periodStr = line.replace(PERIOD_LABEL, '').trim()
      const rangeM = periodStr.match(/(.+?)\s*[〜～~\-－]+\s*(.+)/)
      if (!rangeM) continue
      const startYM = parseYMBody(rangeM[1])
      const endYM = parseYMBody(rangeM[2])
      if (!startYM || !endYM) continue
      const months = endYM - startYM + 1
      if (months <= 0 || months > 600) continue
      // 前後10行で使用技術行を探す
      for (let di = -2; di <= 10; di++) {
        const sline = lines[li + di]?.trim() ?? ''
        const sm = sline.match(SKILL_LABEL)
        if (!sm) continue
        const skillStr = sm[2] ?? ''
        const skills = skillStr.split(/[\s\/／、，,・]+/).map(s => s.replace(/[（(][^）)]*[）)]/g, '').trim()).filter(s => s.length >= 2 && s.length <= 40 && !/^\d+$/.test(s))
        for (const skill of skills) {
          if (!isNonSkill(skill)) {
            result[skill] = (result[skill] ?? 0) + months
          }
        }
      }
    }
  }

  // パターン8: Word職務経歴書の「YYYY~YYYY /会社名：...【言語】A B C【OS】D E...」形式
  // 年代範囲（YYYY~YYYY または YYYY年M月～YYYY年M月）+ 【言語】【OS】【DB】【ツール】等のインライン埋め込み
  {
    const lines = text.split(/\n/)
    const nowYM = new Date().getFullYear() * 12 + new Date().getMonth() + 1
    // 年月パーサー（YYYY年M月, YYYY/M, YYYY.M, YYYY~YYYY の開始年のみ等）
    const parseYMSimple = (s)=> {
      const m1 = s.match(/(\d{4})年(\d{1,2})月/)
      if (m1) return parseInt(m1[1]) * 12 + parseInt(m1[2])
      const m2 = s.match(/(\d{4})[\/\-.:](\d{1,2})/)
      if (m2) return parseInt(m2[1]) * 12 + parseInt(m2[2])
      const m3 = s.match(/^(\d{4})$/)
      if (m3) return parseInt(m3[1]) * 12  // 年のみは1月扱い
      if (/現在|今|継続|在籍中|就業中/i.test(s)) return nowYM
      return null
    }
    // 行またはブロック内の【XXX】タグの後続テキストからスキルを収集
    const extractInlineTagSkills = (segment)=> {
      const skills = []
      // 【言語】【OS】【DB】【ツール】【FW】等のタグ後のスキル列
      const tagPattern = /【(?:言語|OS|DB|ツール|FW|フレームワーク|ミドル|MW|クラウド|インフラ|環境|開発環境|使用技術|技術)】([^【\n]{2,200})/g
      let tm
      while ((tm = tagPattern.exec(segment)) !== null) {
        // スペース/スラッシュ/読点で分割
        const parts = tm[1].split(/[\s　\/／,、・]+/)
        for (const p of parts) {
          const s = p.replace(/[（(][^）)]*[）)]/g, '').trim()
          if (s.length >= 2 && s.length <= 40 && !/^\d+$/.test(s)) skills.push(s)
        }
      }
      return skills
    }

    // ブロック区切りのない連結行を含む処理: 各行でまず年代範囲を検出し、
    // その行（またはその行を含む前後数行）に【言語】等がある場合にスキルを抽出
    for (let li = 0; li < lines.length; li++) {
      const line = lines[li]
      // 年代範囲を含む行を検出 (YYYY~YYYY or YYYY年M月～YYYY年M月)
      const rangeMatch = line.match(/(\d{4}(?:年\d{1,2}月)?)\s*[〜～~\-－]+\s*(\d{4}(?:年\d{1,2}月)?|現在|今|継続|在籍中|就業中)/)
      if (!rangeMatch) continue
      const startYM = parseYMSimple(rangeMatch[1])
      const endYM = parseYMSimple(rangeMatch[2])
      if (!startYM || !endYM) continue
      const months = Math.max(1, endYM - startYM + 1)
      if (months <= 0 || months > 600) continue

      // この行と前後5行を連結してタグを検索
      const segment = lines.slice(Math.max(0, li), Math.min(lines.length, li + 6)).join(' ')
      if (!segment.includes('【')) continue
      const skills = extractInlineTagSkills(segment)
      for (const skill of skills) {
        if (!isNonSkill(skill)) {
          result[skill] = (result[skill] ?? 0) + months
        }
      }
    }

    // パターン8c: T.S型「MM/DD/YY 開始 + 【言語】ブロック + MM/DD/YY 終了 + N年Nヶ月」形式
    // 各行でMM/DD/YY（または類似）日付を見つけ、前後のセグメントに【言語】等があれば収集
    // 期間は明示された「N年Nヶ月」「（Nヶ月）」「Nヶ月間」テキストから取得
    {
      // 【言語】等を含む行のインデックスを収集
      const tagLineIdxs = []
      for (let li = 0; li < lines.length; li++) {
        if (/【(?:言語|OS|DB|ツール|FW|フレームワーク|ミドル|MW|クラウド|インフラ|環境|開発環境|使用技術|技術)】/.test(lines[li])) {
          tagLineIdxs.push(li)
        }
      }
      // 各タグブロックについて前後20行で明示的な期間テキストを探す
      for (const tli of tagLineIdxs) {
        // 前後のセグメントを連結
        const segStart = Math.max(0, tli - 5)
        const segEnd = Math.min(lines.length, tli + 20)
        const segLines = lines.slice(segStart, segEnd)
        const segText = segLines.join(' ')
        // 明示的な期間を探す（N年Nヶ月、Nヶ月間、(Nヶ月)等）
        let blockMonths = 0
        const durPatterns = [
          /(\d+)年(\d+)[ヶかカ]月/,
          /(\d+)[ヶかカ]月間/,
          /（(\d+)ヶ月）/,
          /\((\d+)ヶ月\)/,
          /(\d+)ヶ月/,
        ]
        for (const dp of durPatterns) {
          const dm = segText.match(dp)
          if (dm) {
            if (dp.toString().includes('年')) {
              blockMonths = parseInt(dm[1]) * 12 + parseInt(dm[2] ?? '0')
            } else {
              blockMonths = parseInt(dm[1])
            }
            if (blockMonths >= 1 && blockMonths <= 600) break
          }
        }
        if (!blockMonths) continue  // 期間が不明なブロックはスキップ
        // このブロックのスキルを収集
        const skills = extractInlineTagSkills(segText)
        for (const skill of skills) {
          if (!isNonSkill(skill)) {
            // 同一スキルが既に登録されている場合は最大値を取る（重複ブロックを避ける）
            result[skill] = Math.max(result[skill] ?? 0, blockMonths)
          }
        }
      }
    }

    // パターン8b: S.H型「数字: 期間 + 環境列（スペース区切り）」形式
    // 例: "1：2024年10月 ～2026年07月 ... EXADATAORACLE Linux8Oracle19c..."
    // 期間：ラベルを含む行の後続数行に技術名がスペース区切りで並ぶ場合
    const PERIOD_LABEL_2 = /(\d{4}年\d{1,2}月\s*[〜～~]+\s*(?:\d{4}年\d{1,2}月|現在|就業中))/
    for (let li = 0; li < lines.length; li++) {
      const line = lines[li]
      // "番号: YYYY年M月 ～ YYYY年M月" または "期間：YYYY年M月 ～ YYYY年M月" 形式
      if (!/^\d+[：:]\s*\d{4}年|^期間[：:]\s*\d{4}年/.test(line.trim())) continue
      const pm = line.match(PERIOD_LABEL_2)
      if (!pm) continue
      const parts = pm[1].split(/[〜～~]+/)
      const startYM = parseYMSimple(parts[0].trim())
      const endYM = parseYMSimple(parts[1]?.trim() ?? '')
      if (!startYM || !endYM) continue
      const months = Math.max(1, endYM - startYM + 1)
      if (months <= 0 || months > 600) continue
      // 同行〜次8行にある技術名を収集（"Linux(RHEL8)"、"Oracle19c"のような形）
      const segment = lines.slice(li, Math.min(lines.length, li + 9)).join(' ')
      // skill_masterに登録されているような技術名: 先頭大文字または英数字で始まるトークン
      const techTokens = segment.split(/[\s　]+/)
      for (const tok of techTokens) {
        const clean = tok.replace(/[（(][^）)]*[）)]/g, '').replace(/[,、・。]+$/, '').trim()
        if (clean.length >= 2 && clean.length <= 40 && /^[A-Z]/.test(clean) && !/^\d/.test(clean) && !/^[A-Z]{1}$/.test(clean)) {
          if (!isNonSkill(clean)) {
            result[clean] = (result[clean] ?? 0) + months
          }
        }
      }
    }
  }

  if (Object.keys(result).length > 0) {
    console.log(`[skillYears-body] count=${Object.keys(result).length} keys=${Object.keys(result).join(',')}`)
  }
  return result
}

// ── extractSkillYearsFromSheetData ──
function extractSkillYearsFromSheetData(data){
  // ── 事前スキャン: Excel上部の「IT経験」「経験年数」宣言セルを探す ──
  // 例: 「IT経験」「7年」が同行または隣接セルにある場合
  // ★ 早期 return せず、値を記録してから Method 1〜3 を続行する
  // （経験年数宣言があってもプロジェクト行からスキル別年数を取れる場合がある）
  let headerTotalMonths = null
  const EXP_LABEL = /IT経験|開発経験|エンジニア歴|経験年数|総経験|業務経験/
  for (let i = 0; i < Math.min(30, data.length); i++) {
    const row = data[i]
    for (let j = 0; j < row.length; j++) {
      const v = String(row[j] ?? '').trim()
      if (!EXP_LABEL.test(v)) continue
      // 凡例・定義行（「凡例：◎＝業務経験1年以上」等）は経験年数の宣言ではないためスキップ
      if (/凡例|◎＝|○＝|◇＝|△＝|▲＝/.test(v)) continue
      // 同セル内に年数が含まれる場合: "IT経験: 7年" など
      const inCell = parseDurationToMonths(v)
      if (inCell) { headerTotalMonths = inCell; break }
      // 隣接セル（右±3）に年数がある場合
      for (let k = j + 1; k <= Math.min(row.length - 1, j + 3); k++) {
        const adj = parseDurationToMonths(String(row[k] ?? ''))
        if (adj) { headerTotalMonths = adj; break }
      }
      if (headerTotalMonths) break
    }
    if (headerTotalMonths) break
  }

  // ── Method 1: プロジェクト経歴型 ──
  let langColIdx = -1
  let fwColIdx = -1
  let headerRowIdx = -1
  let durationColIdx = -1  // 「作業月数」等の純整数の月数列
  let startDateColIdx = -1
  let endDateColIdx = -1
  let noColIdx = -1  // 行番号列（通常 col[0] だが "No." ヘッダーが別列にある場合）
  for (let i = 0; i < Math.min(60, data.length); i++) {
    const row = data[i]
    for (let j = 0; j < row.length; j++) {
      // セル内改行がある場合は先頭行のみ使用（"言語\nDB" → "言語"）
      const v = String(row[j] ?? '').split(/[\r\n]/)[0].trim()
      // 全角スペース・半角スペースを除去した正規化ヘッダー（"言　　語" → "言語"）
      const vNorm = v.replace(/[\s　]+/g, '')
      // 複数行セルを結合した正規化ヘッダー（"作業\n月数" → "作業月数"）
      const vFull = String(row[j] ?? '').replace(/[\r\n]+/g, '').replace(/[\s　]+/g, '')
      // 全角ASCII→半角ASCII正規化（"ＯＳ/ＤＢ/言語" → "OS/DB/言語"）: TMK-S型対応
      const vAscii = vNorm.replace(/[\uFF01-\uFF5E]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0))
      if ((vNorm.includes('使用言語') || vNorm === '言語' || vNorm.includes('使用技術') || vNorm.includes('技術スタック') || vNorm === '技術' || vNorm === '言語/技術'
           || vNorm.includes('開発言語') || vNorm.includes('PG言語')  // "OS・DB・開発言語" / "PG言語" 等の複合ヘッダー対応
           // 複合列ヘッダー対応: "言語　FW" / "言語/FW" / "言語・FW" / "言語 ツール" / "言語/DB" 等
           || (vNorm.includes('言語') && (vNorm.includes('FW') || vNorm.includes('ツール') || vNorm.includes('技術') || vNorm.includes('DB') || vNorm.includes('OS')))
           // 全角ASCII含む複合ヘッダー: "ＯＳ/ＤＢ/環境/言語/他" など（TMK-S型）
           || (vNorm.includes('言語') && (vAscii.includes('OS') || vAscii.includes('DB') || vAscii.includes('FW')))
           // "利用技術" / "機種/OS/DB等" / "OS/言語/DB" 等のヘッダー
           || vNorm.includes('利用技術') || /機種.*OS|OS.*言語|言語.*DB|言語.*OS/i.test(vNorm)
           // 全角ASCII正規化後の照合
           || /OS.*言語|言語.*OS|言語.*DB/i.test(vAscii)
         ) && langColIdx < 0) { langColIdx = j; headerRowIdx = i }
      if ((vNorm.includes('FW') || vNorm.includes('ツール') || vNorm.includes('フレームワーク') || vNorm.includes('ミドル')) && fwColIdx < 0 && j !== langColIdx) fwColIdx = j
      // 純整数の月数列を検出（「作業月数」「月数」「期間（月）」「期間」等）
      // vFull も使うことで "作業\n月数" → "作業月数" のような改行含みヘッダーも検出できる（ＹＫ型）
      if ((/^作業月数$|^月数$|^期間[\(（]月|^期間$/.test(vNorm) || /^作業月数$|^月数$|^期間[\(（]月|^期間$/.test(vFull)) && durationColIdx < 0) durationColIdx = j
      // 作業期間列（"2017.04 ～ 2019.12" 形式の日付範囲を含む列）→ periodRangeColIdx として別途管理
      if ((/^作業期間$|^稼働期間$|^プロジェクト期間$|^PJ期間$|^参画期間$|^在籍期間$/.test(vNorm) || /^作業期間$|^稼働期間$|^プロジェクト期間$|^PJ期間$|^参画期間$|^在籍期間$/.test(vFull)) && durationColIdx < 0) durationColIdx = j
      // 開始・終了日付列（"終了年月：システム名" のような複合ヘッダーにも対応）
      if ((/^開始年月$|^開始$/.test(vNorm) || /^開始年月$|^開始$/.test(vFull)) && startDateColIdx < 0) startDateColIdx = j
      if ((/^終了年月$|^終了$/.test(vNorm) || /^終了年月$|^終了$/.test(vFull) || vNorm.startsWith('終了年月') || vNorm.startsWith('終了：')) && endDateColIdx < 0) endDateColIdx = j
      // 行番号列（"No." "No" "№" 等）
      if ((/^(No\.?|No|№|番号|項目番号)$/i.test(vNorm) || /^(No\.?|No|№|番号|項目番号)$/i.test(vFull)) && noColIdx < 0) noColIdx = j
    }
    if (langColIdx >= 0) break
  }
  if (langColIdx >= 0) {
    const skillMonths= {}
    // プロジェクト期間の重複なし合計（経験年数推定用）
    const projectPeriods= []
    let prevProcessedNo = ''  // マージセル重複スキップ用
    for (let i = headerRowIdx + 1; i < data.length; i++) {
      const row = data[i]
      // noCell: col[0] の最初の行だけを使用（マルチライン "1\n(6ヶ月間)\n..." → "1"）
      const noCell = String(row[0] ?? '').split(/[\r\n]/)[0].trim().replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0))
      // 通常: col[0] が行番号（数字）かどうか。
      // 例外1: 開始年月列が col[0] の場合（「開始年月」ヘッダーが検出済み）は日付でもOK
      // 例外2: "No." 列が col[0] 以外にある場合（noColIdx > 0）は該当列の値を確認
      const altNoCell = noColIdx > 0 ? String(row[noColIdx] ?? '').trim().replace(/[０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0)) : ''
      // durationColIdx に日付が入っているケース（行番号なし・noColIdx未検出）:
      // TMK-S型: 行番号なし、作業期間 col[0〜] に日付が直接入っているパターン
      const durDateRaw = durationColIdx >= 0 ? String(row[durationColIdx] ?? '').trim() : ''
      const durCellIsDate = durationColIdx >= 0 && noColIdx < 0 &&
        /^\d{4}[\/\-年.]\d{1,2}|^\d{1,2}\/\d{1,2}\/\d{2,4}/.test(durDateRaw)
      const isDataRow = /^\d+$/.test(noCell) ||
        (startDateColIdx === 0 && /\d/.test(noCell)) || // 開始日付が col[0] の場合
        (noColIdx > 0 && /^\d+$/.test(altNoCell)) || // "No." 列が別にある場合
        durCellIsDate  // TMK-S型: durationCol に日付がある場合（行番号なし）
      const effectiveNoCell = noCell || altNoCell || (durCellIsDate ? durDateRaw : '')
      if (!effectiveNoCell || !isDataRow) continue
      // マージセルで同じ行番号が複数行に展開されている場合の重複スキップ
      // （A.I型: No.列が2,3列ともに"1"として展開される）
      if (noColIdx > 0 && altNoCell === prevProcessedNo) continue
      prevProcessedNo = altNoCell || noCell
      const langCell = String(row[langColIdx] ?? '').trim()
      const fwCell = fwColIdx >= 0 ? String(row[fwColIdx] ?? '').trim() : ''
      // 期間は次の行の "10年9ヶ月" テキストから取得（最大3行後まで・col[1]とcol[2]を確認）
      let months = null
      // HM型: col[0] にマルチライン "1\n(6ヶ月間)\n..." 形式で期間が埋め込まれている場合
      {
        const col0Full = String(row[0] ?? '').trim()
        if (col0Full.includes('\n')) {
          months = parseDurationToMonths(col0Full) || null
        }
      }
      // ★ 作業月数列（純整数 or 日付範囲）が検出済みの場合は優先使用
      // ただし durationColIdx が行番号列（noColIdx=0 または col[0]）と同じ場合は純整数として使わない
      // （S.K型: 「期間」が col[0] だが data rows の col[0] は行番号 "1","2"... なのでその値は月数ではない）
      const durColIsRowNumCol = durationColIdx >= 0 && (durationColIdx === 0 || durationColIdx === noColIdx)
      if (durationColIdx >= 0) {
        const durRaw = String(row[durationColIdx] ?? '').trim()
        const durNum = parseInt(durRaw, 10)
        if (!durColIsRowNumCol && !isNaN(durNum) && durNum > 0 && durNum <= 600 && String(durNum) === durRaw) {
          months = durNum
        }
        // 期間列が日付範囲 "2017.04 ～ 2019.12" / "2020/04〜2023/03" 形式の場合
        if (!months) {
          // マルチライン（"2017.04\n～\n2019.12"）にも対応
          months = calcMonthsFromMultilineCell(durRaw)
          if (!months) {
            const rangeM = durRaw.match(/(.+?)\s*[〜～~\-－]+\s*(.+)/)
            if (rangeM) {
              const endVal = /現在|今|present|継続/i.test(rangeM[2]) ? new Date().getFullYear() + '/' + (new Date().getMonth() + 1) : rangeM[2]
              months = calcMonthsFromDates(rangeM[1], endVal)
            }
          }
          // parseDuration も試す（"1年6ヶ月" 等）
          if (!months) months = parseDurationToMonths(durRaw)
        }
        // durationColIdx列が日付(>600)でmonthsがまだ未取得の場合、隣接列の純整数を月数として試用
        if (!months) {
          for (let adj = 1; adj <= 8 && !months; adj++) {
            const adjIdx = durationColIdx + adj
            if (adjIdx >= row.length) break
            const adjRaw = String(row[adjIdx] ?? '').trim()
            const adjNum = parseInt(adjRaw, 10)
            if (!isNaN(adjNum) && adjNum > 0 && adjNum <= 600 && String(adjNum) === adjRaw) {
              months = adjNum
            }
          }
        }
      }
      if (!months) {
        // TMK-S型（durCellIsDate=true）: durationColIdx に日付がある → ～行を探して終了日を見つける
        if (durCellIsDate) {
          const startDateStr = String(row[durationColIdx] ?? '').trim()
          let endDateStr = ''
          let durTextStr = ''
          for (let di = 1; di <= 20 && !months; di++) {
            if (i + di >= data.length) break
            const subRow = data[i + di]
            const subDurCell = String(subRow[durationColIdx] ?? '').trim()
            if (/^[〜～~]$/.test(subDurCell)) continue  // ～ 行はスキップ
            // 期間テキスト（"08年05ヶ月" 形式）優先
            const durParsed = parseDurationToMonths(subDurCell)
            if (durParsed && durParsed > 0) { months = durParsed; break }
            // 終了日（"2002/8" 形式）
            if (!endDateStr && /^\d{4}[\/\-年.]\d{1,2}|^\d{1,2}\/\d{1,2}\/\d{2,4}/.test(subDurCell)) {
              endDateStr = subDurCell
            } else if (endDateStr && di > 3) {
              // 終了日は見つかったがduration textがない → date計算で確定
              months = calcMonthsFromDates(startDateStr, endDateStr); break
            }
            // 次のプロジェクト開始日（終了日確認後さらに新しい日付）が来たら終了
            if (endDateStr && /^\d{4}[\/\-年.]\d{1,2}/.test(subDurCell) && subDurCell !== endDateStr) {
              months = calcMonthsFromDates(startDateStr, endDateStr); break
            }
          }
          if (!months && endDateStr) months = calcMonthsFromDates(startDateStr, endDateStr)
        } else {
          const maxDi = durationColIdx >= 0 ? 5 : 3  // durationColIdx あり → 最大5行後まで確認
          for (let di = 1; di <= maxDi && !months; di++) {
            if (i + di < data.length) {
              const subRow = data[i + di]
              // durationColIdx の列も確認（S.K/S.I型: 期間列に "4カ月" / "0年10ヶ月" が別行に入る）
              if (durationColIdx >= 0) {
                months = parseDurationToMonths(String(subRow[durationColIdx] ?? ''))
              }
              if (!months) {
                // col[0] も確認（HM型: 期間が "1\n(6ヶ月間)" → 次行 col[0] = "(6ヶ月間)"）
                months = parseDurationToMonths(String(subRow[0] ?? ''))
                     ?? parseDurationToMonths(String(subRow[1] ?? ''))
                     ?? parseDurationToMonths(String(subRow[2] ?? ''))
              }
            }
          }
        }
      }
      // col[1] に "2025年3月\n～\n2026年2月" 形式で開始〜終了が入っている場合
      if (!months) months = calcMonthsFromMultilineCell(String(row[1] ?? ''))
      // col[1] が日付範囲 "2017.04 ～ 2019.12" の場合（単一セル）
      if (!months) {
        const col1 = String(row[1] ?? '').trim()
        const rangeM1 = col1.match(/(.+?)\s*[〜～~\-－]+\s*(.+)/)
        if (rangeM1) {
          const endVal1 = /現在|今|present|継続/i.test(rangeM1[2]) ? new Date().getFullYear() + '/' + (new Date().getMonth() + 1) : rangeM1[2]
          months = calcMonthsFromDates(rangeM1[1], endVal1)
        }
      }
      // 明示的な開始・終了列がある場合
      if (!months && startDateColIdx >= 0 && endDateColIdx >= 0) {
        months = calcMonthsFromDates(String(row[startDateColIdx] ?? ''), String(row[endDateColIdx] ?? ''))
      }
      // col[1]/col[2] が開始・終了日付（M/D/YY形式 等）の場合
      if (!months) months = calcMonthsFromDates(String(row[1] ?? ''), String(row[2] ?? ''))
      // col[1]/col[3] が別々の日付の場合（またはExcelシリアル日付）
      if (!months) months = calcMonthsFromDates(String(row[1] ?? ''), String(row[3] ?? ''))
      // ペア行型: 次行の col[0] or col[1] が "～" で始まる場合、次行の col[1] or col[2] が終了日 (SH型・K.U型)
      if (!months && i + 1 < data.length) {
        const nextRow = data[i + 1]
        const nextCol0 = String(nextRow[0] ?? '').trim()
        const nextCol1 = String(nextRow[1] ?? '').trim()
        const nextCol2 = String(nextRow[2] ?? '').trim()
        if (/^[〜～~]/.test(nextCol0)) {
          // K.U型: nextRow[0]="～1996.3" or nextRow[0]="～", nextRow[1]="38657"
          const endDate = nextCol0.replace(/^[〜～~：:]+/, '').trim()
          if (endDate) months = calcMonthsFromDates(String(row[1] ?? ''), endDate)
          if (!months) months = calcMonthsFromDates(String(row[1] ?? ''), nextCol1)
          if (!months) months = calcMonthsFromDates(String(row[1] ?? ''), nextCol2)
        } else if (/^[〜～~]/.test(nextCol1)) {
          // SH型: nextRow[1]="～", nextRow[2]=endSerial
          if (!months) months = calcMonthsFromDates(String(row[1] ?? ''), nextCol2)
        }
        // K.U型2: nextRow[1] が "～YYYY.M" 形式
        if (!months && /^[〜～~]/.test(nextCol1)) {
          const endDate2 = nextCol1.replace(/^[〜～~：:]+/, '').trim()
          if (endDate2) months = calcMonthsFromDates(String(row[1] ?? ''), endDate2)
        }
      }
      if (!months || months <= 0) continue
      projectPeriods.push({ start: String(row[1] ?? ''), end: String(row[3] ?? ''), months })
      const rawSkillLines = (langCell + '\n' + fwCell).split(/[\n\r、，,]+/).map(s => s.trim())
        .filter(s => s && s !== '-' && s !== '－' && !/^[\s\-－]+$/.test(s))
      const skillTexts = []
      for (const line of rawSkillLines) {
        // "OS : Windows NT" / "言語　：　Access/VBA" 等の「カテゴリ: 値」形式を値部分だけ取り出す
        const colonIdx = Math.max(line.lastIndexOf('：'), line.lastIndexOf(':'))
        if (colonIdx > 0 && colonIdx < line.length - 1) {
          const prefix = line.slice(0, colonIdx).replace(/[\s　]+/g, '')
          // OS/DB/言語/FW/MW等の短いカテゴリラベルの場合はコロン後を値として使う
          if (/^(OS|DB|言語|FW|MW|NW|環境|ツール|その他)$/.test(prefix)) {
            const vals = line.slice(colonIdx + 1).split(/[\s　\/、]+/).map(s => s.trim()).filter(s => s.length >= 2)
            skillTexts.push(...vals)
            continue
          }
        }
        skillTexts.push(line)
      }
      for (const skill of skillTexts) {
        skillMonths[skill] = (skillMonths[skill] ?? 0) + months
      }
    }
    if (Object.keys(skillMonths).length > 0) {
      // プロジェクト合計月数を特殊キーとして付与（経験年数フォールバック用）
      // headerTotalMonths（上部宣言）が取れていれば優先的に使用
      if (headerTotalMonths && !skillMonths['_totalProjectMonths']) {
        skillMonths['_totalProjectMonths'] = headerTotalMonths
      }
      if (projectPeriods.length > 0) {
        const totalProjectMonths = projectPeriods.reduce((s, p) => s + p.months, 0)
        if (!skillMonths['_totalProjectMonths']) skillMonths['_totalProjectMonths'] = totalProjectMonths
        // max日付 − min日付 スパン（空白期間込みのキャリア全体幅）
        const parseYM = (s) => {
          const m = s.match(/(\d{2,4})[\/\-年](\d{1,2})/)
          if (!m) return null
          let year = parseInt(m[1])
          if (year < 100) year = year < 50 ? 2000 + year : 1900 + year
          return year * 12 + parseInt(m[2])
        }
        const starts = projectPeriods.map(p => parseYM(p.start)).filter((v)=> v !== null)
        const ends   = projectPeriods.map(p => parseYM(p.end)).filter((v)=> v !== null)
        if (starts.length > 0 && ends.length > 0) {
          const spanMonths = Math.max(...ends) - Math.min(...starts) + 1
          if (spanMonths > 0) skillMonths['_dateSpanMonths'] = spanMonths
        }
      }
      return filterSkillYears(skillMonths)
    }
  }
  // ── Method 1.6: 複数年数列テーブル型（W.S/T.S/K.M型）──
  // ヘッダー行に「年数」が複数回現れ、各スキル種別（開発言語/DB/OS等）が横並びに配置される形式
  // 例: "開発言語 | 年数 | DB・FW | 年数 | OS | 年数" の各列ペアからスキルと年数を抽出
  {
    const YEAR_NUM_HEADER = /^年数$|^Years?$/i
    const SKIP_SKILL_HEADER = /^業務経験$|^業務工程$|^担当工程$|^役割$|^規模$|^人数$|^備考$|^その他$|^合計$|^環境[・ツール]?$/
    // ヘッダー行を探す: 「年数」が2回以上出現する行
    let m16HeaderRow = -1
    const m16YearCols = []   // 「年数」列の idx
    const m16SkillCols = []  // 各「年数」列に対応するスキル列 idx
    for (let i = 0; i < Math.min(40, data.length); i++) {
      const row = data[i]
      const yearIdxs = []
      for (let j = 0; j < row.length; j++) {
        const v = String(row[j] ?? '').replace(/[\r\n]+/g, '').replace(/[\s　]+/g, '')
        if (YEAR_NUM_HEADER.test(v)) yearIdxs.push(j)
      }
      if (yearIdxs.length >= 2) {
        m16HeaderRow = i
        for (const yj of yearIdxs) {
          // スキル列 = 年数列の直前に最も近い空でないセル（ただし別の年数列は除く）
          for (let k = yj - 1; k >= 0; k--) {
            const sv = String(row[k] ?? '').replace(/[\r\n]+/g, '').replace(/[\s　]+/g, '')
            if (!sv || yearIdxs.includes(k)) continue
            if (!SKIP_SKILL_HEADER.test(sv)) {
              m16YearCols.push(yj)
              m16SkillCols.push(k)
            }
            break
          }
        }
        if (m16YearCols.length >= 2) break
      }
    }
    if (m16HeaderRow >= 0 && m16YearCols.length >= 2) {
      const SM16= {}
      for (let i = m16HeaderRow + 1; i < data.length; i++) {
        const row = data[i]
        for (let ci = 0; ci < m16YearCols.length; ci++) {
          const yCol = m16YearCols[ci]
          const sCol = m16SkillCols[ci]
          const yearRaw = String(row[yCol] ?? '').trim()
          const yearsNum = parseFloat(yearRaw)
          if (isNaN(yearsNum) || yearsNum <= 0 || yearsNum > 50) continue
          const skillRaw = String(row[sCol] ?? '').trim()
          if (!skillRaw || skillRaw.length < 2 || /^\d+$/.test(skillRaw)) continue
          // スキルが複数行で記述されている場合は各行を個別に処理
          for (const skill of skillRaw.split(/[\r\n、，,]+/).map(s => s.trim()).filter(s => s && s.length >= 2 && !/^\d+$/.test(s))) {
            const mths = Math.round(yearsNum * 12)
            SM16[skill] = Math.max(SM16[skill] ?? 0, mths)
          }
        }
      }
      if (Object.keys(SM16).length > 0) {
        if (headerTotalMonths && !SM16['_totalProjectMonths']) SM16['_totalProjectMonths'] = headerTotalMonths
        return filterSkillYears(SM16)
      }
    }
  }
  // ── Method 1.5: 項番ブロック型（KITAGAWA型）──
  // 「項番」が col[0] に出現し、各プロジェクトが複数行ブロックで記述されるパターン
  // 構造: 項番行 → 開始日行 → ～行 → 終了日行 → (N ） 行（月数）
  {
    const hasKoban = data.some(row => String(row[0] ?? '').trim() === '項番')
    if (hasKoban) {
      const SM15= {}
      let langColIdx15 = -1
      // lang列を検出: 項番行の直前にある「業務経歴」セクションヘッダー行で「言語」ヘッダーを探す
      // col[0]="言語" はスキルマトリクスの行ラベルなのでj>=1のものを優先
      const firstKobanRow = data.findIndex(row => String(row[0] ?? '').trim() === '項番')
      for (let i = Math.max(0, firstKobanRow - 5); i < firstKobanRow; i++) {
        for (let j = 1; j < data[i].length; j++) {
          const v = String(data[i][j] ?? '').split(/[\r\n]/)[0].trim()
          if ((v === '言語' || v.includes('使用言語') || v === '技術' || v === '言語/技術'
            || (v.includes('言語') && (v.includes('FW') || v.includes('DB') || v.includes('OS')))) && langColIdx15 < 0) {
            langColIdx15 = j
          }
        }
      }
      // セクションヘッダー行が見つからない場合は全体スキャン（j>=2のみ対象）
      if (langColIdx15 < 0) {
        for (let i = 0; i < Math.min(firstKobanRow < 0 ? 60 : firstKobanRow + 1, data.length); i++) {
          for (let j = 2; j < data[i].length; j++) {
            const v = String(data[i][j] ?? '').split(/[\r\n]/)[0].trim()
            if ((v === '言語' || v.includes('使用言語')
              || (v.includes('言語') && (v.includes('FW') || v.includes('DB') || v.includes('OS')))) && langColIdx15 < 0) {
              langColIdx15 = j
            }
          }
        }
      }
      for (let i = 0; i < data.length; i++) {
        const col0 = String(data[i][0] ?? '').trim()
        if (col0 !== '項番') continue
        // 次のブロック：当行および直後数行から開始日・終了日・月数・lang を取得
        let startDate = '', endDate = '', blockMonths = null
        const blockLang = []
        let inTilde = false
        // 項番行自体（di=0）から lang を取得（KITAGAWA型: lang が項番行と同じ行の結合セルに存在）
        if (langColIdx15 >= 0) {
          const lv0 = String(data[i][langColIdx15] ?? '').trim()
          if (lv0 && lv0 !== '-' && lv0 !== '－') blockLang.push(...lv0.split(/[\r\n、，,]+/).map(s => s.trim()).filter(s => s))
        }
        for (let di = 1; di <= 15 && i + di < data.length; di++) {
          const nrow = data[i + di]
          const nc0 = String(nrow[0] ?? '').trim()
          const nc1 = String(nrow[1] ?? '').trim()
          // 開始日（Excelシリアル or 日付形式 "4/1/06" / "2006/4" / "2006.4" 等）
          const isDateVal = (s) => /^\d{4,6}$/.test(s) || /^\d{1,4}[\/\-．年.]\d{1,2}/.test(s)
          if (!startDate && isDateVal(nc0)) startDate = nc0
          // ～ 行（"～" 単独または "〜"）
          if (/^[〜～~]$/.test(nc0)) { inTilde = true }
          // 終了日
          if (inTilde && !endDate && isDateVal(nc0) && nc0 !== startDate) endDate = nc0
          // (N ）形式の月数 → col[0]="(" col[1]="48" or "48 ヶ月"
          if (nc0 === '(') {
            const mNum = parseInt(nc1)
            if (!isNaN(mNum) && mNum > 0 && mNum <= 600) blockMonths = mNum
          }
          // lang列（マージセルで空になっている行は skip）
          if (langColIdx15 >= 0) {
            const lv = String(nrow[langColIdx15] ?? '').trim()
            if (lv && lv !== '-' && lv !== '－') blockLang.push(...lv.split(/[\r\n、，,]+/).map(s => s.trim()).filter(s => s))
          }
          // 次の「項番」行が来たら終了
          if (di > 1 && nc0 === '項番') break
        }
        if (!blockMonths && startDate && endDate) {
          blockMonths = calcMonthsFromDates(startDate, endDate)
        }
        if (!blockMonths || blockMonths <= 0) continue
        // 重複排除（マージセルにより同じスキルが複数行に現れるため）
        const uniqueSkills = [...new Set(blockLang)]
        for (const skill of uniqueSkills) {
          if (skill && skill.length >= 2 && !/^\d+$/.test(skill)) {
            SM15[skill] = (SM15[skill] ?? 0) + blockMonths
          }
        }
      }
      if (Object.keys(SM15).filter(k => !k.startsWith('_')).length > 0) {
        if (headerTotalMonths && !SM15['_totalProjectMonths']) SM15['_totalProjectMonths'] = headerTotalMonths
        return filterSkillYears(SM15)
      }
    }
  }
  // ── Method 3: スキル一覧型（経験年数列が数値のみ） ──
  // 例: "スキル名 | 5 | ◎" のように経験年数が整数で表現されている形式
  {
    const EXP_YEAR_HEADER = /^(経験年数|経験年|経験\(年\)|年数|年|Years?|Exp\.?)$/i
    const SKILL_COL_HEADER = /^(スキル名?|技術名?|使用技術|言語|技術スタック|item|技術項目)$/i
    let expYrCol = -1
    let skillCol3 = -1
    let hdrRow3 = -1
    for (let i = 0; i < Math.min(60, data.length); i++) {
      const row = data[i]
      for (let j = 0; j < row.length; j++) {
        const v = String(row[j] ?? '').trim()
        if (EXP_YEAR_HEADER.test(v) && expYrCol < 0) { expYrCol = j; hdrRow3 = i }
        if (SKILL_COL_HEADER.test(v) && skillCol3 < 0) skillCol3 = j
      }
      if (expYrCol >= 0 && skillCol3 >= 0) break
    }
    if (expYrCol >= 0 && skillCol3 >= 0 && skillCol3 !== expYrCol) {
      const SM3= {}
      const BLOCKLIST3 = /^(自己PR|PR|備考|補足|資格|氏名|年齢|性別|国籍|住所|学歴|経歴|担当|役割|役職|ポジション|立場|評価|合計|スコア|レベル|プロジェクト名|企業名|規模|人数|期間|開始|終了|弊社社員|自社社員|社員|派遣|契約|フリー)$/
      for (let i = hdrRow3 + 1; i < data.length; i++) {
        const row = data[i]
        const expRaw = String(row[expYrCol] ?? '').trim()
        // 数値のみを年数として解釈（"5" → 60ヶ月、"2.5" → 30ヶ月）
        const yearsNum = parseFloat(expRaw)
        if (isNaN(yearsNum) || yearsNum <= 0 || yearsNum > 50) continue
        const skillName = String(row[skillCol3] ?? '').trim()
        if (!skillName || skillName.length < 2 || /^\d+$/.test(skillName) || BLOCKLIST3.test(skillName)) continue
        const months = Math.round(yearsNum * 12)
        SM3[skillName] = Math.max(SM3[skillName] ?? 0, months)
      }
      if (Object.keys(SM3).length > 0) {
        if (headerTotalMonths && !SM3['_totalProjectMonths']) SM3['_totalProjectMonths'] = headerTotalMonths
        return filterSkillYears(SM3)
      }
    }
  }

  // ── Method 2: スキル一覧型 ──
  // セクション見出し語（スキル名として誤採用しないもの）
  const SKILL_LABEL_BLOCKLIST = /^(自己PR|PR|アピールポイント|強み|備考|補足|資格|氏名|年齢|性別|国籍|住所|学歴|経歴|勤務先|担当|役割|役職|ポジション|立場|所属|評価|合計|スコア|レベル|備考欄|担当工程|プロジェクト名|案件名|企業名|会社名|規模|人数|期間|開始|終了|備考・コメント|弊社社員|自社社員|社員|派遣|契約|フリー)$/
  const isSkillLabelCandidate = (s)=>
    s.length >= 2 && !/^\d+$/.test(s) && !/^[\s\-－◎○●▲×]+$/.test(s) && !SKILL_LABEL_BLOCKLIST.test(s)
  const skillMonths2= {}
  for (const row of data) {
    if (!row || row.length < 2) continue
    // 行内の「期間セル」位置を事前収集（隣のスキルの領域に越境しないための境界として使う）
    const durIdxs = []
    for (let j = 0; j < row.length; j++) {
      if (parseDurationToMonths(String(row[j] ?? ''))) durIdxs.push(j)
    }
    for (const j of durIdxs) {
      const months = parseDurationToMonths(String(row[j] ?? ''))
      let matched = false
      // ① 左方向に境界探索（他の期間セルを跨いだら停止）: "スキル名 ... 期間" の一般的な並びを優先
      //    列間隔が広いシート（ラベルと値が3列以上離れている）でも正しく対応付けられる
      const prevDur = [...durIdxs].reverse().find(d => d < j)
      const leftBound = prevDur !== undefined ? prevDur + 1 : 0
      for (let k = j - 1; k >= leftBound; k--) {
        const candidate = String(row[k] ?? '').trim()
        if (isSkillLabelCandidate(candidate)) {
          skillMonths2[candidate] = Math.max(skillMonths2[candidate] ?? 0, months)
          matched = true
          break
        }
      }
      if (matched) continue
      // ② 左に見つからない場合: 従来通り右側 ±3 セルを探索（"期間 スキル名" の並びに対応）
      const nextDur = durIdxs.find(d => d > j)
      const rightBound = Math.min(row.length - 1, j + 3, nextDur !== undefined ? nextDur - 1 : row.length - 1)
      for (let k = j + 1; k <= rightBound; k++) {
        const candidate = String(row[k] ?? '').trim()
        if (isSkillLabelCandidate(candidate)) {
          skillMonths2[candidate] = Math.max(skillMonths2[candidate] ?? 0, months)
          break
        }
      }
    }
  }
  if (Object.keys(skillMonths2).length > 0) {
    if (headerTotalMonths && !skillMonths2['_totalProjectMonths']) skillMonths2['_totalProjectMonths'] = headerTotalMonths
    return filterSkillYears(skillMonths2)
  }

  // ── headerTotalMonths のみ取れた場合（スキル別年数なし）は早期リターン ──
  if (headerTotalMonths) return { _totalProjectMonths: headerTotalMonths }

  // ── 最終フォールバック: 日付の最小〜最大期間から総経験月数を算出 ──
  // シリアル日付（数値型）とテキスト日付（"2020/04"等）の両方を収集し、
  // 最も古い日付〜最も新しい日付の差分を総経験月数とみなす。
  // Wordの calcWordProjectMonths と同じ考え方（最小〜最大の引き算）
  {
    // 「年月の整数値（year*12+month）」に統一して比較
    const ymValues = []

    // Excelシリアル日付（整数で36526〜48000の範囲: 2000年〜2031年）をYM変換
    const SERIAL_MIN = 36526
    const SERIAL_MAX = 48000
    const serialToYM = (serial) => {
      // Excelシリアル日付 → JSのDate（1899-12-30基点）
      const d = new Date(Date.UTC(1899, 11, 30) + serial * 86400000)
      return d.getUTCFullYear() * 12 + d.getUTCMonth()
    }

    // テキスト日付パターン: "2020/04" "2020-04" "2020.04" "2020年4月" "2020年4"
    // g1991.10 のような元号プレフィックスも許容（g を除去）
    const TEXT_DATE_RE = /(?<![g\d])([gGhHrR]?\d{4})[\/\-年.](\d{1,2})(?:[月]|(?!\d))/

    for (const row of data) {
      for (const cell of row) {
        const raw = cell ?? ''
        // シリアル日付
        const num = parseFloat(String(raw))
        if (!isNaN(num) && num === Math.floor(num) && num >= SERIAL_MIN && num <= SERIAL_MAX) {
          ymValues.push(serialToYM(num))
          continue
        }
        // テキスト日付（g/h/r/s プレフィックスを除去してから年数をパース）
        const tm = String(raw).match(TEXT_DATE_RE)
        if (tm) {
          const y = parseInt(tm[1].replace(/^[gGhHrRsS]/, ''), 10), mo = parseInt(tm[2])
          if (y >= 1990 && y <= 2035 && mo >= 1 && mo <= 12) {
            ymValues.push(y * 12 + mo)
          }
        }
      }
    }

    if (ymValues.length >= 2) {
      const minYM = Math.min(...ymValues)
      const maxYM = Math.max(...ymValues)
      const months = maxYM - minYM
      if (months > 0 && months < 600) {
        return { _totalProjectMonths: months }
      }
    }
  }

  return {}
}


export {
  parseDurationToMonths,
  excelSerialToDateStr,
  calcMonthsFromMultilineCell,
  calcMonthsFromDates,
  filterSkillYears,
  extractSkillYearsFromBodyText,
  extractSkillYearsFromSheetData,
}