-- skill_master シードデータ（約1600件）
-- source = 'seed' の固定スキルマスター
INSERT INTO skill_master (name, category, aliases) VALUES

-- ============================================================
-- languages (~65件)
-- ============================================================
('Python', 'languages', '["python3","py","Python3"]'),
('JavaScript', 'languages', '["JS","js","ECMAScript","Javascript","javascript"]'),
('TypeScript', 'languages', '["TS","ts","Typescript","typescript"]'),
('Java', 'languages', '["java","JAVA"]'),
('PHP', 'languages', '["php"]'),
('Ruby', 'languages', '["ruby"]'),
('Go', 'languages', '["golang","Go言語"]'),
('Rust', 'languages', '["rust"]'),
('Kotlin', 'languages', '["kotlin"]'),
('Swift', 'languages', '["swift"]'),
('C', 'languages', '["c言語","C言語"]'),
('C++', 'languages', '["cpp","c plus plus","CPP"]'),
('C#', 'languages', '["csharp","c sharp","CSharp"]'),
('Scala', 'languages', '["scala"]'),
('R', 'languages', '["R言語","R language"]'),
('COBOL', 'languages', '["cobol","Cobol"]'),
('Perl', 'languages', '["perl"]'),
('Bash', 'languages', '["bash","bash script","シェルスクリプト"]'),
('Shell', 'languages', '["shell","sh","シェル"]'),
('PowerShell', 'languages', '["powershell","ps1"]'),
('Dart', 'languages', '["dart"]'),
('Julia', 'languages', '["julia"]'),
('Groovy', 'languages', '["groovy"]'),
('Lua', 'languages', '["lua"]'),
('Elixir', 'languages', '["elixir"]'),
('Erlang', 'languages', '["erlang"]'),
('Haskell', 'languages', '["haskell"]'),
('F#', 'languages', '["fsharp","f sharp"]'),
('OCaml', 'languages', '["ocaml"]'),
('Clojure', 'languages', '["clojure"]'),
('ABAP', 'languages', '["abap"]'),
('SAS', 'languages', '["sas"]'),
('Apex', 'languages', '["apex","Salesforce Apex"]'),
('VBA', 'languages', '["vba","Excel VBA","ExcelVBA"]'),
('PL/SQL', 'languages', '["plsql","pl sql","PLSQL"]'),
('T-SQL', 'languages', '["tsql","t sql","Transact-SQL"]'),
('HTML', 'languages', '["html5","HTML5"]'),
('CSS', 'languages', '["css3","CSS3"]'),
('SCSS', 'languages', '["scss","Sass/SCSS"]'),
('Sass', 'languages', '["sass"]'),
('GraphQL', 'languages', '["graphql","GraphQL API"]'),
('SQL', 'languages', '["sql","SQL言語"]'),
('HCL', 'languages', '["hcl","HashiCorp Configuration Language"]'),
('Objective-C', 'languages', '["objc","objective c","ObjC"]'),
('Assembly', 'languages', '["asm","アセンブリ","アセンブラ"]'),
('MATLAB', 'languages', '["matlab"]'),
('Fortran', 'languages', '["fortran"]'),
('Verilog', 'languages', '["verilog"]'),
('VHDL', 'languages', '["vhdl"]'),
('RPG', 'languages', '["rpg","RPG IV","ILE RPG"]'),
('ActionScript', 'languages', '["actionscript","as3"]'),
('CoffeeScript', 'languages', '["coffeescript"]'),
('Zig', 'languages', '["zig"]'),
('Node.js', 'languages', '["NodeJS","node.js","nodejs","Node"]'),

-- ============================================================
-- frameworks (~130件)
-- ============================================================
('React', 'frameworks', '["ReactJS","React.js","reactjs","react.js"]'),
('Vue.js', 'frameworks', '["Vue","VueJS","vue","vue.js","Vue3","Vue2"]'),
('Angular', 'frameworks', '["angular","AngularJS","Angular2"]'),
('Next.js', 'frameworks', '["NextJS","next.js","nextjs"]'),
('Nuxt.js', 'frameworks', '["Nuxt","NuxtJS","nuxt","nuxt.js","Nuxt3"]'),
('Svelte', 'frameworks', '["svelte"]'),
('SvelteKit', 'frameworks', '["sveltekit"]'),
('Astro', 'frameworks', '["astro"]'),
('Remix', 'frameworks', '["remix"]'),
('Express', 'frameworks', '["express.js","expressjs","Express.js"]'),
('NestJS', 'frameworks', '["nestjs","nest.js","Nest"]'),
('Fastify', 'frameworks', '["fastify"]'),
('Koa', 'frameworks', '["koa","koa.js"]'),
('Hono', 'frameworks', '["hono"]'),
('Django', 'frameworks', '["django"]'),
('FastAPI', 'frameworks', '["fastapi","fast api"]'),
('Flask', 'frameworks', '["flask"]'),
('Celery', 'frameworks', '["celery"]'),
('Spring', 'frameworks', '["spring framework","Spring Framework"]'),
('Spring Boot', 'frameworks', '["springboot","spring-boot","SpringBoot"]'),
('Spring MVC', 'frameworks', '["spring mvc","SpringMVC"]'),
('Spring Security', 'frameworks', '["spring security"]'),
('Spring Cloud', 'frameworks', '["spring cloud"]'),
('Hibernate', 'frameworks', '["hibernate"]'),
('MyBatis', 'frameworks', '["mybatis","my batis"]'),
('Struts', 'frameworks', '["struts","Struts2"]'),
('Ruby on Rails', 'frameworks', '["Rails","rails","RoR","ruby on rails"]'),
('Sinatra', 'frameworks', '["sinatra"]'),
('Laravel', 'frameworks', '["laravel"]'),
('Symfony', 'frameworks', '["symfony"]'),
('CodeIgniter', 'frameworks', '["codeigniter","CI"]'),
('CakePHP', 'frameworks', '["cakephp","CakePHP4"]'),
('WordPress', 'frameworks', '["wordpress","WP","wp"]'),
('Drupal', 'frameworks', '["drupal"]'),
('ASP.NET', 'frameworks', '["aspnet","asp.net","ASP.NET MVC"]'),
('ASP.NET Core', 'frameworks', '["aspnetcore","asp.net core"]'),
('.NET Core', 'frameworks', '["dotnet core",".net core","dotnetcore"]'),
('.NET Framework', 'frameworks', '["dotnet","dotnet framework",".NET"]'),
('Blazor', 'frameworks', '["blazor"]'),
('Flutter', 'frameworks', '["flutter"]'),
('React Native', 'frameworks', '["react-native","ReactNative","RN"]'),
('Ionic', 'frameworks', '["ionic"]'),
('Xamarin', 'frameworks', '["xamarin"]'),
('PyTorch', 'frameworks', '["pytorch","torch"]'),
('TensorFlow', 'frameworks', '["tensorflow","tf","TF"]'),
('Keras', 'frameworks', '["keras"]'),
('scikit-learn', 'frameworks', '["sklearn","scikit learn","Scikit-learn"]'),
('XGBoost', 'frameworks', '["xgboost"]'),
('LightGBM', 'frameworks', '["lightgbm","lgbm"]'),
('LangChain', 'frameworks', '["langchain","lang chain"]'),
('LlamaIndex', 'frameworks', '["llamaindex","llama index","llama-index"]'),
('Hugging Face', 'frameworks', '["huggingface","hugging face","transformers"]'),
('Unity', 'frameworks', '["unity","Unity3D"]'),
('Unreal Engine', 'frameworks', '["unreal","UE4","UE5","Unreal Engine 5"]'),
('Godot', 'frameworks', '["godot"]'),
('SwiftUI', 'frameworks', '["swiftui"]'),
('UIKit', 'frameworks', '["uikit"]'),
('Jetpack Compose', 'frameworks', '["jetpack compose","compose"]'),
('Electron', 'frameworks', '["electron","electronjs"]'),
('Tauri', 'frameworks', '["tauri"]'),
('Gin', 'frameworks', '["gin","gin-gonic"]'),
('Echo', 'frameworks', '["echo","echo framework"]'),
('Fiber', 'frameworks', '["fiber","gofiber"]'),
('gRPC', 'frameworks', '["grpc","grpc-go","gRPC-Go"]'),
('GraphQL', 'frameworks', '["graphql","GraphQL API"]'),
('tRPC', 'frameworks', '["trpc","t3"]'),

-- ============================================================
-- libraries (~90件)
-- ============================================================
('jQuery', 'libraries', '["jquery","JQuery"]'),
('Bootstrap', 'libraries', '["bootstrap","Bootstrap5","Bootstrap4"]'),
('Tailwind CSS', 'libraries', '["tailwind","tailwindcss","TailwindCSS"]'),
('Material UI', 'libraries', '["mui","material-ui","MaterialUI","MUI"]'),
('Ant Design', 'libraries', '["antd","ant design","AntDesign"]'),
('Chakra UI', 'libraries', '["chakra","chakra-ui"]'),
('Vuetify', 'libraries', '["vuetify"]'),
('Element Plus', 'libraries', '["element-plus","elementplus"]'),
('Styled Components', 'libraries', '["styled-components","styled components"]'),
('Redux', 'libraries', '["redux","redux toolkit","RTK"]'),
('Zustand', 'libraries', '["zustand"]'),
('Recoil', 'libraries', '["recoil"]'),
('MobX', 'libraries', '["mobx"]'),
('Axios', 'libraries', '["axios"]'),
('Socket.io', 'libraries', '["socketio","socket io","socket.io"]'),
('Three.js', 'libraries', '["threejs","three.js"]'),
('D3.js', 'libraries', '["d3","d3js","d3.js"]'),
('Chart.js', 'libraries', '["chartjs","chart.js"]'),
('Lodash', 'libraries', '["lodash"]'),
('Moment.js', 'libraries', '["moment","momentjs","moment.js"]'),
('Day.js', 'libraries', '["dayjs","day.js"]'),
('Zod', 'libraries', '["zod"]'),
('Yup', 'libraries', '["yup"]'),
('Jest', 'libraries', '["jest","jest.js"]'),
('Vitest', 'libraries', '["vitest"]'),
('Mocha', 'libraries', '["mocha"]'),
('Cypress', 'libraries', '["cypress"]'),
('Playwright', 'libraries', '["playwright"]'),
('Selenium', 'libraries', '["selenium","selenium webdriver"]'),
('Puppeteer', 'libraries', '["puppeteer"]'),
('Storybook', 'libraries', '["storybook"]'),
('Webpack', 'libraries', '["webpack"]'),
('Vite', 'libraries', '["vite"]'),
('Rollup', 'libraries', '["rollup"]'),
('esbuild', 'libraries', '["esbuild"]'),
('Babel', 'libraries', '["babel"]'),
('NumPy', 'libraries', '["numpy","np"]'),
('pandas', 'libraries', '["pandas","pd"]'),
('Matplotlib', 'libraries', '["matplotlib","plt"]'),
('Seaborn', 'libraries', '["seaborn","sns"]'),
('OpenCV', 'libraries', '["opencv","cv2"]'),
('Pillow', 'libraries', '["pillow","PIL"]'),
('SQLAlchemy', 'libraries', '["sqlalchemy"]'),
('Pydantic', 'libraries', '["pydantic"]'),
('pytest', 'libraries', '["pytest"]'),
('JUnit', 'libraries', '["junit","JUnit5","junit5"]'),
('Mockito', 'libraries', '["mockito"]'),
('RSpec', 'libraries', '["rspec"]'),
('PHPUnit', 'libraries', '["phpunit"]'),
('Lottie', 'libraries', '["lottie","lottie-web"]'),
('Rive', 'libraries', '["rive"]'),
('React Query', 'libraries', '["tanstack query","react-query","TanStack Query"]'),
('SWR', 'libraries', '["swr"]'),
('Framer Motion', 'libraries', '["framer motion","framer-motion"]'),
('React Hook Form', 'libraries', '["react-hook-form","react hook form"]'),
('Formik', 'libraries', '["formik"]'),
('MSW', 'libraries', '["msw","mock service worker"]'),
('Testing Library', 'libraries', '["testing-library","@testing-library"]'),
('Apollo Client', 'libraries', '["apollo-client","apollo client","ApolloClient"]'),
('urql', 'libraries', '["urql"]'),
('Prisma', 'libraries', '["prisma","prisma orm"]'),
('TypeORM', 'libraries', '["typeorm","type-orm"]'),
('Drizzle ORM', 'libraries', '["drizzle","drizzle-orm"]'),
('Sequelize', 'libraries', '["sequelize"]'),
('Mongoose', 'libraries', '["mongoose"]'),
('Jotai', 'libraries', '["jotai"]'),
('Nanostores', 'libraries', '["nanostores"]'),
('Radix UI', 'libraries', '["radix-ui","radix ui"]'),
('shadcn/ui', 'libraries', '["shadcn","shadcn ui"]'),
('Headless UI', 'libraries', '["headlessui","headless-ui"]'),
('NextAuth.js', 'libraries', '["nextauth","next-auth"]'),
('Auth.js', 'libraries', '["authjs","auth.js"]'),
('Lucide', 'libraries', '["lucide","lucide-react"]'),
('Recharts', 'libraries', '["recharts"]'),
('Highcharts', 'libraries', '["highcharts"]'),
('ECharts', 'libraries', '["echarts","apache echarts"]'),

-- ============================================================
-- os (~22件)
-- ============================================================
('Linux', 'os', '["linux","GNU/Linux"]'),
('Windows', 'os', '["windows","Windows 10","Windows 11","win"]'),
('macOS', 'os', '["macos","mac os","osx","Mac","MacOS"]'),
('Unix', 'os', '["unix","UNIX"]'),
('Ubuntu', 'os', '["ubuntu"]'),
('CentOS', 'os', '["centos","cent os"]'),
('Debian', 'os', '["debian"]'),
('Red Hat', 'os', '["redhat","red hat enterprise","RHEL","RedHat"]'),
('RHEL', 'os', '["rhel","red hat enterprise linux"]'),
('Amazon Linux', 'os', '["amazon linux","amazonlinux","al2","al2023"]'),
('Alpine Linux', 'os', '["alpine","alpine linux"]'),
('FreeBSD', 'os', '["freebsd"]'),
('Android', 'os', '["android"]'),
('iOS', 'os', '["ios","iPhone OS"]'),
('Windows Server', 'os', '["windows server","windowsserver","WS2019","WS2022"]'),
('ChromeOS', 'os', '["chromeos","chrome os"]'),
('Fedora', 'os', '["fedora"]'),
('Arch Linux', 'os', '["archlinux","arch linux"]'),
('openSUSE', 'os', '["opensuse","open suse"]'),

-- ============================================================
-- databases (~55件)
-- ============================================================
('MySQL', 'databases', '["mysql","MYSQL","MySQL8"]'),
('PostgreSQL', 'databases', '["Postgres","PG","postgres","postgresql","PGSQL"]'),
('SQLite', 'databases', '["sqlite","sqlite3"]'),
('MariaDB', 'databases', '["mariadb","maria db"]'),
('Oracle Database', 'databases', '["Oracle DB","Oracle","oracle db","OracleDB"]'),
('SQL Server', 'databases', '["MSSQL","Microsoft SQL Server","mssql","sqlserver"]'),
('MongoDB', 'databases', '["Mongo","mongo","mongodb","MongoDB Atlas"]'),
('Redis', 'databases', '["redis","Redis Cache"]'),
('Elasticsearch', 'databases', '["elasticsearch","ES","elastic search","OpenSearch"]'),
('DynamoDB', 'databases', '["Amazon DynamoDB","dynamodb","dynamo"]'),
('Cassandra', 'databases', '["cassandra","Apache Cassandra"]'),
('CouchDB', 'databases', '["couchdb","couch db"]'),
('Neo4j', 'databases', '["neo4j","neo4j graph"]'),
('InfluxDB', 'databases', '["influxdb","influx"]'),
('TimescaleDB', 'databases', '["timescaledb","timescale"]'),
('CockroachDB', 'databases', '["cockroachdb","cockroach db"]'),
('TiDB', 'databases', '["tidb"]'),
('PlanetScale', 'databases', '["planetscale"]'),
('ClickHouse', 'databases', '["clickhouse","click house"]'),
('Druid', 'databases', '["druid","apache druid"]'),
('Memcached', 'databases', '["memcached","memcache"]'),
('RocksDB', 'databases', '["rocksdb","rocks db"]'),
('etcd', 'databases', '["etcd"]'),
('Valkey', 'databases', '["valkey"]'),
('FaunaDB', 'databases', '["faunadb","fauna"]'),
('PouchDB', 'databases', '["pouchdb"]'),
('ArangoDB', 'databases', '["arangodb","arango"]'),
('Dolt', 'databases', '["dolt","dolthub"]'),
('Neon', 'databases', '["neon","neon db","neondb"]'),
('Turso', 'databases', '["turso"]'),
('SingleStore', 'databases', '["singlestore","memsql"]'),
('Citus', 'databases', '["citus","citus data"]'),
('Firestore', 'databases', '["firestore","Cloud Firestore","google firestore"]'),
('Realm', 'databases', '["realm","realm database"]'),
('SurrealDB', 'databases', '["surrealdb","surreal db"]'),

-- ============================================================
-- dwh (~25件)
-- ============================================================
('Snowflake', 'dwh', '["snowflake","Snowflake DWH"]'),
('Amazon Redshift', 'dwh', '["Redshift","redshift","AWS Redshift"]'),
('Google BigQuery', 'dwh', '["BigQuery","bigquery","bq"]'),
('Azure Synapse', 'dwh', '["azure synapse","synapse analytics","Azure Synapse Analytics"]'),
('Databricks', 'dwh', '["databricks"]'),
('Apache Hive', 'dwh', '["hive","apache hive"]'),
('Apache Spark', 'dwh', '["spark","apache spark","PySpark","pyspark"]'),
('dbt', 'dwh', '["dbt","data build tool","dbt Core"]'),
('Looker', 'dwh', '["looker","looker studio"]'),
('Looker Studio', 'dwh', '["looker studio","Google Data Studio","data studio"]'),
('Tableau', 'dwh', '["tableau","Tableau Desktop","Tableau Server"]'),
('Power BI', 'dwh', '["powerbi","power bi","Microsoft Power BI"]'),
('Metabase', 'dwh', '["metabase"]'),
('Redash', 'dwh', '["redash"]'),
('Apache Superset', 'dwh', '["superset","apache superset"]'),
('Grafana', 'dwh', '["grafana"]'),
('Airflow', 'dwh', '["airflow","apache airflow","Apache Airflow"]'),
('Apache Kafka', 'dwh', '["kafka","apache kafka","Kafka"]'),
('Apache Flink', 'dwh', '["flink","apache flink"]'),
('Apache Beam', 'dwh', '["beam","apache beam","dataflow"]'),
('Presto', 'dwh', '["presto","prestodb","trino"]'),
('Trino', 'dwh', '["trino"]'),
('Fivetran', 'dwh', '["fivetran"]'),
('Stitch', 'dwh', '["stitch","stitch data"]'),

-- ============================================================
-- clouds (~90件)
-- ============================================================
('AWS', 'clouds', '["Amazon Web Services","aws","amazon aws"]'),
('Amazon EC2', 'clouds', '["EC2","ec2","Amazon EC2"]'),
('Amazon S3', 'clouds', '["S3","s3","Amazon S3","AWS S3"]'),
('Amazon RDS', 'clouds', '["RDS","rds","Amazon RDS","AWS RDS"]'),
('Amazon DynamoDB', 'clouds', '["DynamoDB","dynamodb","AWS DynamoDB"]'),
('AWS Lambda', 'clouds', '["Lambda","lambda","AWS Lambda Function"]'),
('Amazon CloudFront', 'clouds', '["CloudFront","cloudfront","AWS CloudFront"]'),
('Amazon Route 53', 'clouds', '["Route53","route53","Route 53"]'),
('Amazon VPC', 'clouds', '["VPC","vpc","Amazon VPC"]'),
('Amazon IAM', 'clouds', '["IAM","iam","AWS IAM"]'),
('Amazon ECS', 'clouds', '["ECS","ecs","Amazon ECS"]'),
('Amazon EKS', 'clouds', '["EKS","eks","Amazon EKS"]'),
('AWS Fargate', 'clouds', '["Fargate","fargate"]'),
('Amazon SQS', 'clouds', '["SQS","sqs","Amazon SQS"]'),
('Amazon SNS', 'clouds', '["SNS","sns","Amazon SNS"]'),
('Amazon API Gateway', 'clouds', '["API Gateway","apigateway","AWS API Gateway"]'),
('Amazon CloudWatch', 'clouds', '["CloudWatch","cloudwatch","AWS CloudWatch"]'),
('AWS CloudFormation', 'clouds', '["CloudFormation","cloudformation","CFn"]'),
('AWS CDK', 'clouds', '["cdk","aws cdk","Cloud Development Kit"]'),
('AWS Amplify', 'clouds', '["Amplify","amplify","AWS Amplify"]'),
('Amazon Cognito', 'clouds', '["Cognito","cognito"]'),
('Amazon Bedrock', 'clouds', '["Bedrock","bedrock","AWS Bedrock"]'),
('Amazon SageMaker', 'clouds', '["SageMaker","sagemaker"]'),
('Amazon Redshift', 'clouds', '["Redshift","redshift"]'),
('Amazon Aurora', 'clouds', '["Aurora","aurora","Aurora MySQL","Aurora PostgreSQL"]'),
('Amazon ElastiCache', 'clouds', '["ElastiCache","elasticache"]'),
('AWS Glue', 'clouds', '["Glue","glue","AWS Glue ETL"]'),
('Amazon Athena', 'clouds', '["Athena","athena"]'),
('Amazon Kinesis', 'clouds', '["Kinesis","kinesis","Kinesis Data Streams"]'),
('AWS Step Functions', 'clouds', '["Step Functions","stepfunctions"]'),
('AWS WAF', 'clouds', '["WAF","waf","AWS WAF"]'),
('AWS Secrets Manager', 'clouds', '["Secrets Manager","secrets manager"]'),
('Azure', 'clouds', '["Microsoft Azure","azure"]'),
('Azure App Service', 'clouds', '["app service","azure app service"]'),
('Azure Functions', 'clouds', '["azure functions","azure function"]'),
('Azure Kubernetes Service', 'clouds', '["AKS","aks","Azure AKS"]'),
('Azure Virtual Machines', 'clouds', '["Azure VM","azure vm","azure virtual machine"]'),
('Azure Blob Storage', 'clouds', '["Azure Blob","azure blob","blob storage"]'),
('Azure SQL Database', 'clouds', '["Azure SQL","azure sql"]'),
('Azure Cosmos DB', 'clouds', '["CosmosDB","cosmos db","Azure Cosmos"]'),
('Azure Active Directory', 'clouds', '["AAD","azure ad","Azure AD","Entra ID"]'),
('Azure DevOps', 'clouds', '["azure devops","AzureDevOps"]'),
('Azure Pipelines', 'clouds', '["azure pipelines","Azure CI/CD"]'),
('Azure OpenAI', 'clouds', '["azure openai","Azure OpenAI Service"]'),
('Azure Machine Learning', 'clouds', '["azure ml","Azure ML","AzureML"]'),
('Azure Synapse Analytics', 'clouds', '["Azure Synapse","synapse"]'),
('Azure Data Factory', 'clouds', '["ADF","azure data factory","Azure ADF"]'),
('GCP', 'clouds', '["Google Cloud Platform","Google Cloud","gcp","google cloud"]'),
('Google Cloud', 'clouds', '["GCP","google cloud platform"]'),
('Cloud Run', 'clouds', '["cloud run","cloudrun","GCP Cloud Run"]'),
('Google Kubernetes Engine', 'clouds', '["GKE","gke","Google GKE"]'),
('Cloud Functions', 'clouds', '["cloud functions","google cloud functions","GCF"]'),
('Google App Engine', 'clouds', '["app engine","GAE","gae"]'),
('Cloud Storage', 'clouds', '["google cloud storage","GCS","gcs"]'),
('Cloud SQL', 'clouds', '["cloud sql","google cloud sql"]'),
('Pub/Sub', 'clouds', '["pubsub","pub sub","google pubsub","Cloud Pub/Sub"]'),
('Vertex AI', 'clouds', '["vertex ai","vertexai"]'),
('Firebase', 'clouds', '["firebase","google firebase"]'),
('Supabase', 'clouds', '["supabase"]'),
('Vercel', 'clouds', '["vercel"]'),
('Netlify', 'clouds', '["netlify"]'),
('Heroku', 'clouds', '["heroku"]'),
('Cloudflare', 'clouds', '["cloudflare","CF"]'),
('Cloudflare Workers', 'clouds', '["cf workers","cloudflare workers","Cloudflare Worker"]'),
('DigitalOcean', 'clouds', '["digitalocean","digital ocean","DO"]'),
('Oracle Cloud', 'clouds', '["oci","oracle cloud infrastructure","OCI"]'),
('IBM Cloud', 'clouds', '["ibm cloud","ibmcloud"]'),
('Alibaba Cloud', 'clouds', '["aliyun","alibabacloud","alibaba cloud"]'),
('Render', 'clouds', '["render","render.com"]'),
('Railway', 'clouds', '["railway","railway.app"]'),
('Fly.io', 'clouds', '["fly","flyio","fly.io"]'),

-- ============================================================
-- infrastructures (~70件)
-- ============================================================
('Docker', 'infrastructures', '["docker","Docker Container"]'),
('Kubernetes', 'infrastructures', '["k8s","K8s","kubernetes","k8"]'),
('Helm', 'infrastructures', '["helm","helm chart","Helm Chart"]'),
('Kustomize', 'infrastructures', '["kustomize"]'),
('Terraform', 'infrastructures', '["terraform","tf","TF","hashicorp terraform"]'),
('Pulumi', 'infrastructures', '["pulumi"]'),
('Ansible', 'infrastructures', '["ansible"]'),
('Puppet', 'infrastructures', '["puppet"]'),
('Chef', 'infrastructures', '["chef","chef infra"]'),
('Vagrant', 'infrastructures', '["vagrant"]'),
('Packer', 'infrastructures', '["packer","hashicorp packer"]'),
('Jenkins', 'infrastructures', '["jenkins","Jenkins CI"]'),
('GitHub Actions', 'infrastructures', '["GHA","gha","github actions","Github Actions"]'),
('GitLab CI/CD', 'infrastructures', '["GitLab CI","gitlab ci","gitlab ci/cd","GitLabCI"]'),
('CircleCI', 'infrastructures', '["circleci","circle ci"]'),
('Travis CI', 'infrastructures', '["travisci","travis ci","Travis"]'),
('ArgoCD', 'infrastructures', '["argocd","argo cd","Argo CD"]'),
('Flux', 'infrastructures', '["flux","fluxcd","Flux CD"]'),
('Tekton', 'infrastructures', '["tekton"]'),
('Prometheus', 'infrastructures', '["prometheus"]'),
('Alertmanager', 'infrastructures', '["alertmanager","alert manager"]'),
('Loki', 'infrastructures', '["loki","grafana loki"]'),
('Jaeger', 'infrastructures', '["jaeger","jaeger tracing"]'),
('OpenTelemetry', 'infrastructures', '["otel","opentelemetry","open telemetry"]'),
('Datadog', 'infrastructures', '["datadog","data dog"]'),
('New Relic', 'infrastructures', '["newrelic","new relic","NewRelic"]'),
('Dynatrace', 'infrastructures', '["dynatrace"]'),
('Splunk', 'infrastructures', '["splunk"]'),
('ELK Stack', 'infrastructures', '["elk","elastic stack","ELK"]'),
('Logstash', 'infrastructures', '["logstash"]'),
('Kibana', 'infrastructures', '["kibana"]'),
('Fluentd', 'infrastructures', '["fluentd","fluent bit","FluentBit"]'),
('Nginx', 'infrastructures', '["nginx","NGINX","nginx server"]'),
('Apache HTTP Server', 'infrastructures', '["apache","apache httpd","Apache"]'),
('HAProxy', 'infrastructures', '["haproxy","ha proxy"]'),
('Traefik', 'infrastructures', '["traefik"]'),
('Envoy', 'infrastructures', '["envoy","envoy proxy"]'),
('Istio', 'infrastructures', '["istio","service mesh"]'),
('Linkerd', 'infrastructures', '["linkerd"]'),
('HashiCorp Vault', 'infrastructures', '["vault","hashicorp vault","Vault"]'),
('Consul', 'infrastructures', '["consul","hashicorp consul"]'),
('Nomad', 'infrastructures', '["nomad","hashicorp nomad"]'),
('Knative', 'infrastructures', '["knative"]'),
('KEDA', 'infrastructures', '["keda"]'),
('RabbitMQ', 'infrastructures', '["rabbitmq","rabbit mq"]'),
('ActiveMQ', 'infrastructures', '["activemq","active mq"]'),
('NATS', 'infrastructures', '["nats","nats.io"]'),
('Zookeeper', 'infrastructures', '["zookeeper","apache zookeeper"]'),
('Argo Workflows', 'infrastructures', '["argo workflows","argoworkflows"]'),
('GitHub', 'infrastructures', '["github","GitHub.com"]'),
('GitLab', 'infrastructures', '["gitlab","GitLab.com"]'),
('Bitbucket', 'infrastructures', '["bitbucket"]'),
('Git', 'infrastructures', '["git","Git VCS"]'),
('SVN', 'infrastructures', '["svn","subversion","Subversion"]'),
('CI/CD', 'infrastructures', '["CICD","ci cd","CI・CD","継続的インテグレーション","継続的デリバリー"]'),
('Terraform Cloud', 'infrastructures', '["terraform cloud","tfc"]'),
('Crossplane', 'infrastructures', '["crossplane"]'),
('Skaffold', 'infrastructures', '["skaffold"]'),
('Buildkite', 'infrastructures', '["buildkite"]'),
('Spinnaker', 'infrastructures', '["spinnaker"]'),
('Dagger', 'infrastructures', '["dagger"]'),
('Podman', 'infrastructures', '["podman"]'),
('containerd', 'infrastructures', '["containerd","container-d"]'),
('OpenShift', 'infrastructures', '["openshift","redhat openshift","OCP"]'),
('Rancher', 'infrastructures', '["rancher"]'),
('k3s', 'infrastructures', '["k3s","lightweight kubernetes"]'),

-- ============================================================
-- tools (~60件)
-- ============================================================
('Jira', 'tools', '["jira","JIRA","Jira Software"]'),
('Confluence', 'tools', '["confluence"]'),
('Notion', 'tools', '["notion"]'),
('Trello', 'tools', '["trello"]'),
('Asana', 'tools', '["asana"]'),
('Monday.com', 'tools', '["monday","monday.com"]'),
('ClickUp', 'tools', '["clickup","click up"]'),
('Backlog', 'tools', '["backlog","ヌーラボ backlog"]'),
('Linear', 'tools', '["linear","linear.app"]'),
('Slack', 'tools', '["slack"]'),
('Microsoft Teams', 'tools', '["teams","ms teams","Microsoft Teams"]'),
('Zoom', 'tools', '["zoom","zoom meeting"]'),
('Google Workspace', 'tools', '["google workspace","gsuite","G Suite","G Workspace"]'),
('Microsoft 365', 'tools', '["m365","office 365","Microsoft Office","Office365"]'),
('SharePoint', 'tools', '["sharepoint","share point"]'),
('Salesforce', 'tools', '["salesforce","sfdc","SFDC"]'),
('SAP', 'tools', '["sap","SAP ERP","SAP S/4HANA"]'),
('ServiceNow', 'tools', '["servicenow","service now"]'),
('HubSpot', 'tools', '["hubspot","hub spot"]'),
('Zendesk', 'tools', '["zendesk"]'),
('Postman', 'tools', '["postman"]'),
('Insomnia', 'tools', '["insomnia","insomnia rest"]'),
('Swagger', 'tools', '["swagger","openapi","OpenAPI","Swagger UI"]'),
('Figma', 'tools', '["figma"]'),
('Miro', 'tools', '["miro"]'),
('Airtable', 'tools', '["airtable"]'),
('Smartsheet', 'tools', '["smartsheet"]'),
('Excel', 'tools', '["excel","Microsoft Excel","エクセル"]'),
('PowerPoint', 'tools', '["powerpoint","Microsoft PowerPoint","パワポ","パワーポイント"]'),
('Access', 'tools', '["access","Microsoft Access"]'),
('Power Automate', 'tools', '["power automate","powerautomate","Microsoft Power Automate"]'),
('Power Apps', 'tools', '["power apps","powerapps"]'),
('PagerDuty', 'tools', '["pagerduty","pager duty"]'),
('OpsGenie', 'tools', '["opsgenie","ops genie"]'),
('Sentry', 'tools', '["sentry","sentry.io"]'),
('Rollbar', 'tools', '["rollbar"]'),
('BugSnag', 'tools', '["bugsnag","bug snag"]'),
('Grafana', 'tools', '["grafana","grafana dashboard"]'),
('Tableau', 'tools', '["tableau"]'),
('VS Code', 'tools', '["vscode","visual studio code","VSCode","VisualStudioCode"]'),
('IntelliJ IDEA', 'tools', '["intellij","intellij idea","IDEA"]'),
('Eclipse', 'tools', '["eclipse","eclipse ide"]'),
('Xcode', 'tools', '["xcode"]'),
('Android Studio', 'tools', '["android studio","androidstudio"]'),
('Vim', 'tools', '["vim","neovim","nvim"]'),
('Emacs', 'tools', '["emacs"]'),
('ChatGPT', 'tools', '["chatgpt","chat gpt","ChatGPT API","OpenAI ChatGPT"]'),
('Gemini', 'tools', '["gemini","google gemini"]'),
('Copilot', 'tools', '["github copilot","copilot","GitHub Copilot"]'),
('Cursor', 'tools', '["cursor","cursor ide","cursor ai"]'),
('make.com', 'tools', '["make","integromat","Make.com"]'),
('Zapier', 'tools', '["zapier"]'),
('n8n', 'tools', '["n8n"]'),
('Wireshark', 'tools', '["wireshark"]'),
('Burp Suite', 'tools', '["burpsuite","burp suite","Burp"]'),
('Metasploit', 'tools', '["metasploit"]'),
('Nmap', 'tools', '["nmap"]'),

-- ============================================================
-- methodologies (~35件)
-- ============================================================
('Agile', 'methodologies', '["agile","アジャイル"]'),
('Scrum', 'methodologies', '["scrum","スクラム"]'),
('Kanban', 'methodologies', '["kanban","カンバン"]'),
('Lean', 'methodologies', '["lean","リーン"]'),
('DevOps', 'methodologies', '["devops","DevOps文化"]'),
('MLOps', 'methodologies', '["mlops","ML Ops"]'),
('DataOps', 'methodologies', '["dataops","Data Ops"]'),
('AIOps', 'methodologies', '["aiops","AI Ops"]'),
('GitOps', 'methodologies', '["gitops","Git Ops"]'),
('SRE', 'methodologies', '["sre","site reliability engineering","サイトリライアビリティ"]'),
('TDD', 'methodologies', '["tdd","test driven development","テスト駆動開発"]'),
('BDD', 'methodologies', '["bdd","behavior driven development"]'),
('DDD', 'methodologies', '["ddd","domain driven design","ドメイン駆動設計"]'),
('Clean Architecture', 'methodologies', '["clean architecture","クリーンアーキテクチャ"]'),
('Microservices', 'methodologies', '["microservices","マイクロサービス"]'),
('Serverless', 'methodologies', '["serverless","サーバーレス"]'),
('Event-Driven Architecture', 'methodologies', '["eda","event driven","イベント駆動"]'),
('CQRS', 'methodologies', '["cqrs","Command Query Responsibility Segregation"]'),
('Event Sourcing', 'methodologies', '["event sourcing"]'),
('SOA', 'methodologies', '["soa","service oriented architecture"]'),
('REST', 'methodologies', '["rest api","RESTful","REST API","RESTful API"]'),
('SOLID', 'methodologies', '["solid principles","solid","SOLID原則"]'),
('Design Patterns', 'methodologies', '["design patterns","デザインパターン","GoF"]'),
('FinOps', 'methodologies', '["finops","fin ops"]'),
('Platform Engineering', 'methodologies', '["platform engineering","プラットフォームエンジニアリング"]'),
('ウォーターフォール', 'methodologies', '["waterfall","ウォーターフォール開発","WF"]'),
('要件定義', 'methodologies', '["要件定義","要件整理"]'),
('基本設計', 'methodologies', '["基本設計","概要設計"]'),
('詳細設計', 'methodologies', '["詳細設計","内部設計"]'),
('テスト設計', 'methodologies', '["テスト設計","テスト計画"]'),
('コードレビュー', 'methodologies', '["コードレビュー","code review","PR review"]'),
('プロジェクトマネジメント', 'methodologies', '["プロジェクト管理","PM","PjM","プロジェクトマネージャ"]'),
('システム設計', 'methodologies', '["システム設計","アーキテクチャ設計"]'),
('セキュリティ設計', 'methodologies', '["セキュリティ設計","security design"]'),

-- ============================================================
-- certifications (~35件)
-- ============================================================
('AWS Solutions Architect', 'certifications', '["aws saa","SAA","AWS SAA","Solutions Architect Associate","AWS認定ソリューションアーキテクト"]'),
('AWS Developer', 'certifications', '["aws dva","DVA","AWS DVA","AWS Certified Developer"]'),
('AWS SysOps', 'certifications', '["aws soa","SOA","AWS SysOps Administrator"]'),
('AWSクラウドプラクティショナー', 'certifications', '["aws cp","CLF","AWS CLF","Cloud Practitioner"]'),
('Azure Administrator', 'certifications', '["az-104","AZ-104","azure admin"]'),
('Azure Developer', 'certifications', '["az-204","AZ-204","azure developer associate"]'),
('Azure Architect', 'certifications', '["az-305","AZ-305","azure solutions architect"]'),
('GCP Associate', 'certifications', '["gcp ace","GCP ACE","associate cloud engineer"]'),
('GCP Professional', 'certifications', '["gcp pce","gcp pro","professional cloud architect"]'),
('Oracle Java SE', 'certifications', '["oracle java","OJCP","Java SE認定"]'),
('CCNA', 'certifications', '["ccna","Cisco CCNA"]'),
('CCNP', 'certifications', '["ccnp","Cisco CCNP"]'),
('CCIE', 'certifications', '["ccie","Cisco CCIE"]'),
('CompTIA Security+', 'certifications', '["security+","comptia security","SY0"]'),
('CISSP', 'certifications', '["cissp"]'),
('CEH', 'certifications', '["ceh","certified ethical hacker"]'),
('OSCP', 'certifications', '["oscp","offensive security"]'),
('CKA', 'certifications', '["cka","Certified Kubernetes Administrator"]'),
('CKS', 'certifications', '["cks","Certified Kubernetes Security Specialist"]'),
('CKAD', 'certifications', '["ckad","Certified Kubernetes Application Developer"]'),
('Terraform Associate', 'certifications', '["terraform associate","hashicorp terraform"]'),
('Salesforce認定', 'certifications', '["salesforce certified","sfdc認定","Salesforce認定アドミニストレーター"]'),
('PMP', 'certifications', '["pmp","Project Management Professional"]'),
('ITIL', 'certifications', '["itil","ITIL4"]'),
('Scrum Master', 'certifications', '["csm","scrum master","認定スクラムマスター","PSM"]'),
('基本情報技術者', 'certifications', '["FE","基本情報","基本情報処理","基本情報技術者試験"]'),
('応用情報技術者', 'certifications', '["AP","応用情報","応用情報処理","応用情報技術者試験"]'),
('情報処理安全確保支援士', 'certifications', '["SC","情報安全確保支援士","セキュリティ試験"]'),
('プロジェクトマネージャ試験', 'certifications', '["PM試験","PMO試験","プロジェクトマネージャ"]'),
('ネットワークスペシャリスト', 'certifications', '["NW","ネットワークスペシャリスト試験"]'),
('データベーススペシャリスト', 'certifications', '["DB","データベーススペシャリスト試験"]'),
('ITストラテジスト', 'certifications', '["ST","ITストラテジスト試験"]'),
('システムアーキテクト', 'certifications', '["SA","システムアーキテクト試験"]'),
('TOEIC', 'certifications', '["toeic","TOEIC L&R"]'),
('TOEFL', 'certifications', '["toefl"]'),

-- ============================================================
-- design (~35件)
-- ============================================================
('Figma', 'design', '["figma","Figma Design"]'),
('Sketch', 'design', '["sketch","Sketch App"]'),
('Adobe XD', 'design', '["xd","adobe xd","AdobeXD"]'),
('InVision', 'design', '["invision","in vision"]'),
('Zeplin', 'design', '["zeplin"]'),
('Framer', 'design', '["framer","framer.com"]'),
('Webflow', 'design', '["webflow"]'),
('Photoshop', 'design', '["photoshop","ps","Adobe Photoshop"]'),
('Illustrator', 'design', '["illustrator","ai","Adobe Illustrator","AI"]'),
('InDesign', 'design', '["indesign","Adobe InDesign"]'),
('After Effects', 'design', '["after effects","aftereffects","ae","AE","AfterEffects"]'),
('Premiere Pro', 'design', '["premiere pro","premiere","Adobe Premiere","PremierePro"]'),
('Final Cut Pro', 'design', '["final cut","finalcutpro","FCP"]'),
('DaVinci Resolve', 'design', '["davinci resolve","davinci","DaVinci"]'),
('GIMP', 'design', '["gimp"]'),
('Inkscape', 'design', '["inkscape"]'),
('Blender', 'design', '["blender"]'),
('Maya', 'design', '["maya","Autodesk Maya"]'),
('Cinema 4D', 'design', '["cinema4d","c4d","C4D"]'),
('Canva', 'design', '["canva"]'),
('Miro', 'design', '["miro"]'),
('Balsamiq', 'design', '["balsamiq"]'),
('Axure', 'design', '["axure","axure rp"]'),
('UXPin', 'design', '["uxpin"]'),
('Proto.io', 'design', '["proto.io","proto io"]'),
('ProtoPie', 'design', '["protopie","proto pie"]'),
('Lottie', 'design', '["lottie","lottie animation"]'),
('Spline', 'design', '["spline","spline 3d"]'),
('UI/UXデザイン', 'design', '["UIデザイン","UXデザイン","UIUXデザイン","UI設計","UX設計"]'),
('グラフィックデザイン', 'design', '["graphic design","グラフィックデザイン"]'),
('Webデザイン', 'design', '["Webデザイン","web design","ウェブデザイン"]'),
('動画編集', 'design', '["動画編集","動画制作","映像編集"]'),
('イラスト制作', 'design', '["イラスト","illustration"]'),
('アニメーション', 'design', '["animation","アニメーション","モーショングラフィックス"]'),
('3DCG', 'design', '["3DCG","3D CG","三次元CG"]'),

-- ============================================================
-- marketing (~20件)
-- ============================================================
('SEO', 'marketing', '["seo","Search Engine Optimization","検索エンジン最適化"]'),
('SEM', 'marketing', '["sem","search engine marketing","リスティング"]'),
('SNS運用', 'marketing', '["SNS","sns運用","ソーシャルメディア","social media"]'),
('Web広告', 'marketing', '["web広告","ネット広告","オンライン広告","デジタル広告"]'),
('Google広告', 'marketing', '["google ads","google広告","GoogleAds","Google Adwords"]'),
('Facebook広告', 'marketing', '["facebook ads","facebook広告","Meta広告"]'),
('ECサイト運営', 'marketing', '["ec運営","ECサイト","eコマース","EC"]'),
('デジタルマーケティング', 'marketing', '["digital marketing","デジタルマーケ"]'),
('コンテンツマーケティング', 'marketing', '["コンテンツマーケ","content marketing"]'),
('マーケティングオートメーション', 'marketing', '["MA","marketing automation","マーケオートメーション"]'),
('CRM', 'marketing', '["crm","顧客管理","Customer Relationship Management"]'),
('Google Analytics', 'marketing', '["ga4","google analytics","GA","GA4","Googleアナリティクス"]'),
('A/Bテスト', 'marketing', '["ab test","A/Bテスト","split test"]'),
('メールマーケティング', 'marketing', '["email marketing","メールマーケ","Mailchimp"]'),
('インフルエンサーマーケティング', 'marketing', '["インフルエンサー","influencer marketing"]'),
('Webアクセス解析', 'marketing', '["アクセス解析","web analytics"]'),
('LPO', 'marketing', '["lpo","Landing Page Optimization","ランディングページ最適化"]'),
('GTM', 'marketing', '["gtm","google tag manager","Google Tag Manager"]'),
('BI分析', 'marketing', '["bi","bi分析","business intelligence"]'),

-- ============================================================
-- others (~40件)
-- ============================================================
('機械学習', 'others', '["machine learning","ML","ml","マシンラーニング"]'),
('深層学習', 'others', '["deep learning","DL","dl","ディープラーニング"]'),
('自然言語処理', 'others', '["nlp","NLP","natural language processing","NLPタスク"]'),
('画像認識', 'others', '["computer vision","CV","画像解析","image recognition"]'),
('生成AI', 'others', '["generative ai","GenAI","生成型AI","AI生成"]'),
('LLM', 'others', '["llm","large language model","大規模言語モデル"]'),
('RAG', 'others', '["rag","retrieval augmented generation","検索拡張生成"]'),
('プロンプトエンジニアリング', 'others', '["prompt engineering","プロンプト設計"]'),
('TCP/IP', 'others', '["tcp ip","tcpip","ネットワークプロトコル"]'),
('HTTP', 'others', '["http","HTTP/1.1"]'),
('HTTPS', 'others', '["https","TLS","ssl/tls","SSL/TLS"]'),
('REST API', 'others', '["rest api","RESTful API","API設計"]'),
('Raspberry Pi', 'others', '["raspberry pi","ラズパイ","RasPi","raspi"]'),
('Arduino', 'others', '["arduino"]'),
('ESP32', 'others', '["esp32","esp8266"]'),
('FPGA', 'others', '["fpga","Field Programmable Gate Array"]'),
('PLC', 'others', '["plc","プログラマブルロジックコントローラ"]'),
('ROS', 'others', '["ros","ros2","Robot Operating System"]'),
('IoT', 'others', '["iot","IoTシステム","Internet of Things"]'),
('Blockchain', 'others', '["blockchain","ブロックチェーン"]'),
('Web3', 'others', '["web3","web 3.0"]'),
('Solidity', 'others', '["solidity","スマートコントラクト"]'),
('NFT', 'others', '["nft","Non-Fungible Token"]'),
('AR', 'others', '["ar","augmented reality","拡張現実"]'),
('VR', 'others', '["vr","virtual reality","仮想現実"]'),
('XR', 'others', '["xr","extended reality","メタバース"]'),
('Edge Computing', 'others', '["edge computing","エッジコンピューティング"]'),
('Quantum Computing', 'others', '["quantum computing","量子コンピューター"]'),
('アルゴリズム', 'others', '["algorithm","アルゴリズム設計","データ構造"]'),
('データ分析', 'others', '["data analysis","データ解析","データ活用"]'),
('統計学', 'others', '["statistics","統計","統計解析"]'),
('数値解析', 'others', '["numerical analysis","数値計算"]'),
('クラウドネイティブ', 'others', '["cloud native","クラウドネイティブ設計"]'),
('ゼロトラスト', 'others', '["zero trust","ゼロトラストセキュリティ"]'),
('OWASP', 'others', '["owasp","OWASP Top10"]'),
('ペネトレーションテスト', 'others', '["pentest","pen test","ペネトレーション","侵入テスト"]'),
('ネットワーク設計', 'others', '["network design","ネットワーク構築","NW設計"]'),
('クラウド移行', 'others', '["cloud migration","クラウド移行","リフト＆シフト"]'),
('オブジェクト指向', 'others', '["OOP","オブジェクト指向設計","OOD"]'),
('関数型プログラミング', 'others', '["functional programming","FP","関数型"]')

ON CONFLICT (name) DO NOTHING;
