-- seed_skill_master_extended.sql
-- 既存624件に追加する拡張シードデータ（約600件追加）
INSERT INTO skill_master (name, category, aliases) VALUES

-- ===== certifications (資格) 追加 ~80件 =====
('AWS DevOps Professional', 'certifications', '["aws dop","DOP","DevOps Professional","AWS Certified DevOps Engineer"]'),
('AWS Database Specialty', 'certifications', '["aws dbs","DBS","Database Specialty"]'),
('AWS Machine Learning Specialty', 'certifications', '["aws mls","MLS","Machine Learning Specialty"]'),
('AWS Security Specialty', 'certifications', '["aws scs","SCS","Security Specialty"]'),
('AWS Advanced Networking Specialty', 'certifications', '["aws ans","ANS","Advanced Networking Specialty"]'),
('AWS Data Analytics Specialty', 'certifications', '["aws das","DAS","Data Analytics Specialty"]'),
('AWS SAP on AWS Specialty', 'certifications', '["aws pas","PAS","SAP on AWS"]'),
('AWS Cloud Practitioner', 'certifications', '["aws clf","CLF-C02","Cloud Practitioner","クラウドプラクティショナー"]'),
('AWS Solutions Architect Professional', 'certifications', '["aws sap","SAP-C02","Solutions Architect Professional"]'),
('Azure AI Engineer', 'certifications', '["ai-102","AI-102","Azure AI Engineer Associate"]'),
('Azure Data Engineer', 'certifications', '["dp-203","DP-203","Azure Data Engineer Associate"]'),
('Azure Data Scientist', 'certifications', '["dp-100","DP-100","Azure Data Scientist Associate"]'),
('Azure Database Administrator', 'certifications', '["dp-300","DP-300","Azure Database Administrator"]'),
('Azure DevOps Engineer', 'certifications', '["az-400","AZ-400","Azure DevOps Engineer Expert"]'),
('Azure Fundamentals', 'certifications', '["az-900","AZ-900","Azure Fundamentals"]'),
('Azure AI Fundamentals', 'certifications', '["ai-900","AI-900","Azure AI Fundamentals"]'),
('Azure Data Fundamentals', 'certifications', '["dp-900","DP-900","Azure Data Fundamentals"]'),
('Azure Security Engineer', 'certifications', '["az-500","AZ-500","Azure Security Engineer Associate"]'),
('Azure Network Engineer', 'certifications', '["az-700","AZ-700","Azure Network Engineer Associate"]'),
('Azure Solutions Architect Expert', 'certifications', '["az-305","AZ-305","Azure Solutions Architect Expert"]'),
('GCP Professional Data Engineer', 'certifications', '["gcp pde","Professional Data Engineer"]'),
('GCP Professional Cloud Security Engineer', 'certifications', '["gcp pcse","Professional Cloud Security Engineer"]'),
('GCP Professional Cloud DevOps Engineer', 'certifications', '["gcp pcde","Professional Cloud DevOps Engineer"]'),
('GCP Professional Cloud Network Engineer', 'certifications', '["gcp pcne","Professional Cloud Network Engineer"]'),
('GCP Professional ML Engineer', 'certifications', '["gcp pmle","Professional Machine Learning Engineer"]'),
('GCP Cloud Digital Leader', 'certifications', '["gcp cdl","Cloud Digital Leader"]'),
('LPIC-1', 'certifications', '["lpic1","LinuC-1","Linux Professional 1","LPIC Level 1"]'),
('LPIC-2', 'certifications', '["lpic2","LinuC-2","Linux Professional 2","LPIC Level 2"]'),
('LPIC-3', 'certifications', '["lpic3","LinuC-3","Linux Professional 3","LPIC Level 3"]'),
('LinuC', 'certifications', '["linuc","Linux技術者認定"]'),
('Oracle DB Bronze', 'certifications', '["oracle bronze","Oracle認定資格Bronze","OracleMaster Bronze"]'),
('Oracle DB Silver', 'certifications', '["oracle silver","Oracle認定資格Silver","OracleMaster Silver"]'),
('Oracle DB Gold', 'certifications', '["oracle gold","Oracle認定資格Gold","OracleMaster Gold"]'),
('MySQL認定', 'certifications', '["mysql ocp","MySQL 8.0 Database Administrator"]'),
('統計検定2級', 'certifications', '["統計検定","Japan Statistical Society Certificate","統計検定準1級","統計検定1級"]'),
('データサイエンティスト検定', 'certifications', '["DS検定","データサイエンティスト検定リテラシー","DS検定★"]'),
('G検定', 'certifications', '["g検定","JDLA G検定","Deep Learning for GENERAL"]'),
('E資格', 'certifications', '["e資格","JDLA E資格","Deep Learning for ENGINEER"]'),
('AWS AI Practitioner', 'certifications', '["aif-c01","AIF-C01","AI Practitioner"]'),
('Salesforce管理者', 'certifications', '["salesforce admin","Salesforce Certified Administrator","salesforce adm-201"]'),
('Salesforce開発者', 'certifications', '["salesforce developer","Salesforce Certified Platform Developer","PD1","PD2"]'),
('Salesforce アーキテクト', 'certifications', '["salesforce architect","Salesforce Certified Technical Architect","CTA"]'),
('CompTIA A+', 'certifications', '["comptia a+","A+","CompTIA Aプラス"]'),
('CompTIA Network+', 'certifications', '["comptia network+","Network+","N10"]'),
('CompTIA Cloud+', 'certifications', '["comptia cloud+","CV0"]'),
('CompTIA Linux+', 'certifications', '["comptia linux+","XK0"]'),
('CompTIA Data+', 'certifications', '["comptia data+","DA0"]'),
('CISM', 'certifications', '["cism","Certified Information Security Manager","情報セキュリティマネージャー"]'),
('CISA', 'certifications', '["cisa","Certified Information Systems Auditor"]'),
('情報処理安全確保支援士', 'certifications', '["登録セキスペ","SC","情報セキュリティスペシャリスト","セキスペ"]'),
('システム監査技術者', 'certifications', '["AU","システム監査"]'),
('ITサービスマネージャ', 'certifications', '["SM","サービスマネージャ試験"]'),
('エンベデッドシステムスペシャリスト', 'certifications', '["ES","エンベデッドスペシャリスト","組込みシステム"]'),
('IoTシステムエンジニア試験', 'certifications', '["IoT試験"]'),
('PMP認定', 'certifications', '["PMP認定","PMI","Project Management Professional認定"]'),
('AWS認定機械学習', 'certifications', '["機械学習スペシャリティ","ML専門知識"]'),
('Google Analytics認定', 'certifications', '["GA認定","Google Analytics Individual Qualification","GAIQ"]'),
('Google広告認定', 'certifications', '["Google Ads認定","Google広告資格"]'),
('Tableau Desktop認定', 'certifications', '["Tableau認定","Tableau Desktop Specialist","Tableau Certified Data Analyst"]'),
('Microsoft 365認定', 'certifications', '["ms-900","MS-900","Microsoft 365 Fundamentals"]'),
('Power Platform認定', 'certifications', '["pl-900","PL-900","Power Platform Fundamentals","pl-200","PL-200"]'),
('Dynamics 365認定', 'certifications', '["mb-910","MB-910","Dynamics 365 Fundamentals"]'),
('日商簿記2級', 'certifications', '["簿記2級","日商簿記","日商簿記検定2級"]'),
('日商簿記1級', 'certifications', '["簿記1級","日商簿記検定1級"]'),
('FP技能士2級', 'certifications', '["FP2級","ファイナンシャルプランナー2級"]'),
('TOEIC 800点以上', 'certifications', '["TOEIC800","toeic 800","英語力"]'),
('英検準1級', 'certifications', '["英検準1","eiken pre-1","英語検定準1級"]'),
('中小企業診断士', 'certifications', '["診断士","中小企業診断士試験"]'),
('Scrum Product Owner', 'certifications', '["cspo","Certified Scrum Product Owner","PSPO"]'),
('SAFe認定', 'certifications', '["SAFe Agilist","SA","Scaled Agile Framework"]'),
('HashiCorp Vault Associate', 'certifications', '["vault associate","hashicorp vault"]'),
('Docker Certified Associate', 'certifications', '["dca","Docker認定","Docker Certified"]'),
('Red Hat認定', 'certifications', '["rhce","RHCE","rhcsa","RHCSA","Red Hat Certified Engineer","Red Hat Certified System Administrator"]'),

-- ===== languages (言語) 追加 ~30件 =====
('COBOL', 'languages', '["cobol","コボル"]'),
('Fortran', 'languages', '["fortran","フォートラン"]'),
('Pascal', 'languages', '["pascal","パスカル"]'),
('Delphi', 'languages', '["delphi","デルファイ"]'),
('Ada', 'languages', '["ada","Ada言語"]'),
('Haskell', 'languages', '["haskell","ハスケル"]'),
('Erlang', 'languages', '["erlang","アーラン"]'),
('Elixir', 'languages', '["elixir","エリクサー"]'),
('Clojure', 'languages', '["clojure","クロージャー"]'),
('F#', 'languages', '["fsharp","f sharp","F-sharp"]'),
('OCaml', 'languages', '["ocaml","O Caml"]'),
('Groovy', 'languages', '["groovy","グルービー"]'),
('Perl', 'languages', '["perl","パール"]'),
('Lua', 'languages', '["lua","ルア"]'),
('Julia', 'languages', '["julia","ジュリア"]'),
('MATLAB', 'languages', '["matlab","マトラボ"]'),
('R言語', 'languages', '["R","r言語","統計R","R programming"]'),
('Dart', 'languages', '["dart","ダート"]'),
('Crystal', 'languages', '["crystal lang","クリスタル"]'),
('Nim', 'languages', '["nim lang","ニム"]'),
('Zig', 'languages', '["zig lang","ジグ"]'),
('Mojo', 'languages', '["mojo lang","モジョ"]'),
('WebAssembly', 'languages', '["wasm","WebAssembly","ウェブアセンブリ"]'),
('Solidity', 'languages', '["solidity","ソリディティ","スマートコントラクト"]'),
('HCL', 'languages', '["hcl","HashiCorp Configuration Language","Terraform HCL"]'),
('Bicep', 'languages', '["bicep","azure bicep","Azure Bicep"]'),
('Jsonnet', 'languages', '["jsonnet","json net"]'),
('CUE', 'languages', '["cue lang","cuelang"]'),
('PowerShell', 'languages', '["powershell","パワーシェル","PS"]'),
('VBScript', 'languages', '["vbscript","VBS"]'),

-- ===== frameworks (フレームワーク) 追加 ~80件 =====
('Hono', 'frameworks', '["hono","hono.dev","Hono.js"]'),
('tRPC', 'frameworks', '["trpc","t-rpc","TypeSafe RPC"]'),
('Fastify', 'frameworks', '["fastify","ファストイファイ"]'),
('Elysia', 'frameworks', '["elysia","elysia.js"]'),
('Nitro', 'frameworks', '["nitro","nitro.build","UnJS Nitro"]'),
('Nuxt', 'frameworks', '["nuxt","nuxt3","nuxtjs","Nuxt.js"]'),
('Analog', 'frameworks', '["analog","analogjs","Analog Angular"]'),
('Qwik', 'frameworks', '["qwik","qwik.js"]'),
('SolidJS', 'frameworks', '["solidjs","solid.js","SolidStart"]'),
('Lit', 'frameworks', '["lit","lit-element","Lit framework"]'),
('Alpine.js', 'frameworks', '["alpinejs","alpine","Alpine"]'),
('HTMX', 'frameworks', '["htmx","hypertext markup extensions"]'),
('Hotwire', 'frameworks', '["hotwire","turbo rails","stimulus"]'),
('Inertia.js', 'frameworks', '["inertia","inertia.js"]'),
('Livewire', 'frameworks', '["livewire","laravel livewire"]'),
('Litestar', 'frameworks', '["litestar","starlite"]'),
('Starlette', 'frameworks', '["starlette","starlette framework"]'),
('Sanic', 'frameworks', '["sanic","sanic framework"]'),
('AIOHTTP', 'frameworks', '["aiohttp","async http","python aiohttp"]'),
('Micronaut', 'frameworks', '["micronaut","micronaut framework"]'),
('Quarkus', 'frameworks', '["quarkus","quarkus framework"]'),
('Vert.x', 'frameworks', '["vertx","vert x","eclipse vert.x"]'),
('Ktor', 'frameworks', '["ktor","ktor framework","kotlin ktor"]'),
('Gin', 'frameworks', '["gin","gin gonic","gin-gonic"]'),
('Echo', 'frameworks', '["echo","echo framework","labstack echo"]'),
('Fiber', 'frameworks', '["fiber","gofiber","go fiber"]'),
('Chi', 'frameworks', '["chi router","go chi"]'),
('gRPC', 'frameworks', '["grpc","google rpc","protobuf"]'),
('GraphQL', 'frameworks', '["graphql","graph ql","グラフQL"]'),
('Apollo', 'frameworks', '["apollo","apollo graphql","apolloserver","apollo-server"]'),
('Relay', 'frameworks', '["relay","facebook relay","relay graphql"]'),
('Actix', 'frameworks', '["actix","actix-web","rust actix"]'),
('Axum', 'frameworks', '["axum","tokio axum"]'),
('Rocket', 'frameworks', '["rocket","rocket.rs"]'),
('Symfony', 'frameworks', '["symfony","symfony framework"]'),
('Yii', 'frameworks', '["yii","yii framework","yii2"]'),
('CakePHP', 'frameworks', '["cakephp","cake php"]'),
('Slim', 'frameworks', '["slim","slim framework","slim php"]'),
('ASP.NET', 'frameworks', '["asp.net","aspnet","asp net"]'),
('ASP.NET Core', 'frameworks', '["aspnet core","asp.net core","dotnet core"]'),
('Blazor', 'frameworks', '["blazor","blazor wasm","blazor server"]'),
('WPF', 'frameworks', '["wpf","windows presentation foundation"]'),
('WinForms', 'frameworks', '["winforms","windows forms"]'),
('MAUI', 'frameworks', '["maui",".net maui","dotnet maui"]'),
('Xamarin', 'frameworks', '["xamarin","xamarin forms","microsoft xamarin"]'),
('Flutter', 'frameworks', '["flutter","flutter dart","フラッター"]'),
('React Native', 'frameworks', '["react native","rn","react-native"]'),
('Ionic', 'frameworks', '["ionic","ionic framework"]'),
('Electron', 'frameworks', '["electron","electron.js","electronjs"]'),
('Tauri', 'frameworks', '["tauri","tauri app"]'),
('TensorFlow', 'frameworks', '["tensorflow","tf","テンソルフロー"]'),
('PyTorch', 'frameworks', '["pytorch","torch","パイトーチ"]'),
('Keras', 'frameworks', '["keras","ケラス"]'),
('scikit-learn', 'frameworks', '["sklearn","scikit learn","機械学習sklearn"]'),
('LangChain', 'frameworks', '["langchain","lang chain"]'),
('LlamaIndex', 'frameworks', '["llamaindex","llama index","gpt index"]'),
('Haystack', 'frameworks', '["haystack","deepset haystack"]'),
('Hugging Face', 'frameworks', '["huggingface","hugging face","transformers"]'),
('OpenCV', 'frameworks', '["opencv","open cv","コンピュータビジョン"]'),
('MediaPipe', 'frameworks', '["mediapipe","media pipe"]'),
('Apache Spark', 'frameworks', '["spark","pyspark","apache spark","スパーク"]'),
('Apache Kafka', 'frameworks', '["kafka","apache kafka","カフカ"]'),
('Apache Airflow', 'frameworks', '["airflow","apache airflow"]'),
('Apache Flink', 'frameworks', '["flink","apache flink"]'),
('Celery', 'frameworks', '["celery","celery task","distributed task"]'),
('Scrapy', 'frameworks', '["scrapy","python scrapy"]'),
('Playwright', 'frameworks', '["playwright","microsoft playwright"]'),
('Cypress', 'frameworks', '["cypress","cypress testing"]'),
('Puppeteer', 'frameworks', '["puppeteer","headless chrome"]'),
('Detox', 'frameworks', '["detox","react native detox"]'),
('Appium', 'frameworks', '["appium","mobile test"]'),
('JUnit', 'frameworks', '["junit","junit4","junit5","java unit test"]'),
('Mockito', 'frameworks', '["mockito","mock framework java"]'),
('pytest', 'frameworks', '["pytest","python test","py.test"]'),
('unittest', 'frameworks', '["unittest","python unittest"]'),
('RSpec', 'frameworks', '["rspec","ruby spec","ruby test"]'),
('PHPUnit', 'frameworks', '["phpunit","php unit test"]'),
('Jest', 'frameworks', '["jest","jestjs","jest testing"]'),
('Mocha', 'frameworks', '["mocha","mocha testing","mochajs"]'),
('Vitest', 'frameworks', '["vitest","vite test"]'),

-- ===== libraries (ライブラリ) 追加 ~50件 =====
('Prisma', 'libraries', '["prisma","prisma orm","prisma client"]'),
('Drizzle ORM', 'libraries', '["drizzle","drizzle-orm"]'),
('TypeORM', 'libraries', '["typeorm","type orm"]'),
('Sequelize', 'libraries', '["sequelize","sequelize orm"]'),
('Mongoose', 'libraries', '["mongoose","mongoose mongodb"]'),
('SQLAlchemy', 'libraries', '["sqlalchemy","sql alchemy"]'),
('Pydantic', 'libraries', '["pydantic","pydantic model"]'),
('pandas', 'libraries', '["pandas","python pandas","pd"]'),
('NumPy', 'libraries', '["numpy","num py","np"]'),
('Matplotlib', 'libraries', '["matplotlib","plt","python plot"]'),
('Seaborn', 'libraries', '["seaborn","sns","python seaborn"]'),
('Plotly', 'libraries', '["plotly","plotly express"]'),
('Polars', 'libraries', '["polars","rust dataframe","polars python"]'),
('Dask', 'libraries', '["dask","dask dataframe","parallel pandas"]'),
('SciPy', 'libraries', '["scipy","scientific python"]'),
('NLTK', 'libraries', '["nltk","natural language toolkit"]'),
('spaCy', 'libraries', '["spacy","spa cy","nlp spacy"]'),
('Transformers', 'libraries', '["transformers","huggingface transformers"]'),
('Diffusers', 'libraries', '["diffusers","huggingface diffusers","stable diffusion"]'),
('OpenAI SDK', 'libraries', '["openai sdk","openai python","openai library"]'),
('Anthropic SDK', 'libraries', '["anthropic","anthropic sdk","claude sdk"]'),
('Chakra UI', 'libraries', '["chakra","chakraui","chakra-ui"]'),
('shadcn/ui', 'libraries', '["shadcn","shadcn ui","shadcn-ui"]'),
('Radix UI', 'libraries', '["radix","radix-ui","radix primitives"]'),
('Headless UI', 'libraries', '["headlessui","headless ui"]'),
('Material UI', 'libraries', '["mui","material ui","material-ui","@mui"]'),
('Ant Design', 'libraries', '["antd","ant design","ant-design"]'),
('DaisyUI', 'libraries', '["daisyui","daisy ui"]'),
('Framer Motion', 'libraries', '["framer motion","framer-motion","animation react"]'),
('GSAP', 'libraries', '["gsap","greensock","green sock animation"]'),
('Three.js', 'libraries', '["threejs","three.js","webgl"]'),
('D3.js', 'libraries', '["d3","d3.js","data visualization js"]'),
('Chart.js', 'libraries', '["chartjs","chart.js"]'),
('Recharts', 'libraries', '["recharts","react charts"]'),
('Axios', 'libraries', '["axios","axios http"]'),
('SWR', 'libraries', '["swr","stale while revalidate","vercel swr"]'),
('TanStack Query', 'libraries', '["tanstack query","react query","@tanstack/react-query"]'),
('Zustand', 'libraries', '["zustand","ズスタンド","react state zustand"]'),
('Jotai', 'libraries', '["jotai","atomic state"]'),
('Recoil', 'libraries', '["recoil","facebook recoil"]'),
('MobX', 'libraries', '["mobx","mobx state tree","mob x"]'),
('Redux Toolkit', 'libraries', '["rtk","redux toolkit","@reduxjs/toolkit"]'),
('Immer', 'libraries', '["immer","immer.js","immutable state"]'),
('Zod', 'libraries', '["zod","zod validation","typescript zod"]'),
('Yup', 'libraries', '["yup","yup validation"]'),
('React Hook Form', 'libraries', '["rhf","react hook form","react-hook-form"]'),
('Formik', 'libraries', '["formik","formik form"]'),
('date-fns', 'libraries', '["date-fns","datefns","date functions"]'),
('Day.js', 'libraries', '["dayjs","day.js"]'),
('Lodash', 'libraries', '["lodash","_","lo dash"]'),
('Ramda', 'libraries', '["ramda","ramda.js","functional js"]'),

-- ===== databases (データベース) 追加 ~30件 =====
('MongoDB', 'databases', '["mongo","mongodb","モンゴDB","Mongo"]'),
('Redis', 'databases', '["redis","redis cache","レディス"]'),
('Elasticsearch', 'databases', '["elasticsearch","elastic search","ES","OpenSearch"]'),
('DynamoDB', 'databases', '["dynamodb","dynamo db","aws dynamodb"]'),
('Firestore', 'databases', '["firestore","cloud firestore","firebase firestore"]'),
('Supabase', 'databases', '["supabase","supabase db"]'),
('PlanetScale', 'databases', '["planetscale","planet scale"]'),
('Neon', 'databases', '["neon","neon postgres","neon db"]'),
('Cassandra', 'databases', '["cassandra","apache cassandra","カサンドラ"]'),
('HBase', 'databases', '["hbase","hadoop hbase"]'),
('Neo4j', 'databases', '["neo4j","neo 4j","graph database","グラフDB"]'),
('InfluxDB', 'databases', '["influxdb","influx db","時系列DB"]'),
('TimescaleDB', 'databases', '["timescaledb","timescale","時系列postgresql"]'),
('CockroachDB', 'databases', '["cockroachdb","cockroach db"]'),
('TiDB', 'databases', '["tidb","ti db"]'),
('SQLite', 'databases', '["sqlite","sqlite3","sql lite"]'),
('MariaDB', 'databases', '["mariadb","maria db"]'),
('Aurora', 'databases', '["aurora","amazon aurora","aurora mysql","aurora postgresql"]'),
('Cloud SQL', 'databases', '["cloud sql","gcp cloud sql"]'),
('Azure SQL', 'databases', '["azure sql","azure sql database"]'),
('Cosmos DB', 'databases', '["cosmosdb","cosmos db","azure cosmos"]'),
('Pinecone', 'databases', '["pinecone","vector db","pinecone vector"]'),
('Weaviate', 'databases', '["weaviate","vector database"]'),
('Qdrant', 'databases', '["qdrant","qdrant vector"]'),
('pgvector', 'databases', '["pgvector","pg vector","postgres vector"]'),
('Memcached', 'databases', '["memcached","mem cached"]'),
('RabbitMQ', 'databases', '["rabbitmq","rabbit mq","message queue"]'),
('ActiveMQ', 'databases', '["activemq","active mq","jms"]'),
('Dolt', 'databases', '["dolt","dolt db","git database"]'),

-- ===== clouds (クラウド) 追加 ~30件 =====
('AWS Lambda', 'clouds', '["lambda","aws lambda","サーバーレス lambda"]'),
('AWS ECS', 'clouds', '["ecs","elastic container service","aws ecs"]'),
('AWS EKS', 'clouds', '["eks","elastic kubernetes service","aws eks"]'),
('AWS EC2', 'clouds', '["ec2","elastic compute cloud"]'),
('AWS S3', 'clouds', '["s3","amazon s3","simple storage service"]'),
('AWS CloudFront', 'clouds', '["cloudfront","aws cloudfront","cdn aws"]'),
('AWS RDS', 'clouds', '["rds","relational database service","aws rds"]'),
('AWS SQS', 'clouds', '["sqs","simple queue service","aws sqs"]'),
('AWS SNS', 'clouds', '["sns","simple notification service","aws sns"]'),
('AWS API Gateway', 'clouds', '["api gateway","aws api gateway","apigw"]'),
('AWS Step Functions', 'clouds', '["step functions","aws step functions"]'),
('AWS Glue', 'clouds', '["aws glue","glue etl"]'),
('AWS Athena', 'clouds', '["athena","aws athena"]'),
('AWS Redshift', 'clouds', '["redshift","amazon redshift"]'),
('AWS Bedrock', 'clouds', '["bedrock","amazon bedrock","aws bedrock"]'),
('AWS SageMaker', 'clouds', '["sagemaker","amazon sagemaker"]'),
('AWS CloudFormation', 'clouds', '["cloudformation","cloud formation","cfn"]'),
('AWS CDK', 'clouds', '["cdk","aws cdk","cloud development kit"]'),
('AWS SAM', 'clouds', '["sam","serverless application model","aws sam"]'),
('Azure Functions', 'clouds', '["azure functions","azure function app"]'),
('Azure AKS', 'clouds', '["aks","azure kubernetes service"]'),
('Azure Container Apps', 'clouds', '["aca","azure container apps"]'),
('Azure Blob Storage', 'clouds', '["blob storage","azure blob","azure storage"]'),
('Azure DevOps', 'clouds', '["azure devops","ado","azure pipelines"]'),
('Google Cloud Run', 'clouds', '["cloud run","gcp cloud run","gcr"]'),
('Google GKE', 'clouds', '["gke","google kubernetes engine"]'),
('Google Cloud Functions', 'clouds', '["cloud functions","gcp functions"]'),
('Google BigQuery', 'clouds', '["bigquery","big query","bq"]'),
('Google Cloud Storage', 'clouds', '["gcs","google cloud storage"]'),
('Vercel', 'clouds', '["vercel","vercel deploy","ヴァーセル"]'),
('Netlify', 'clouds', '["netlify","ネットリファイ"]'),
('Cloudflare Workers', 'clouds', '["cf workers","cloudflare workers","cloudflare pages"]'),
('Heroku', 'clouds', '["heroku","ヘロク"]'),
('Railway', 'clouds', '["railway","railway.app"]'),
('Fly.io', 'clouds', '["fly.io","flyio"]'),
('Render', 'clouds', '["render","render.com"]'),

-- ===== infrastructures (インフラ) 追加 ~40件 =====
('Kubernetes', 'infrastructures', '["k8s","kubernetes","クーベネティス","kube"]'),
('Docker Compose', 'infrastructures', '["docker compose","docker-compose","compose"]'),
('Helm', 'infrastructures', '["helm","helm chart","kubernetes helm"]'),
('Kustomize', 'infrastructures', '["kustomize","k8s kustomize"]'),
('ArgoCD', 'infrastructures', '["argocd","argo cd","gitops argocd"]'),
('Flux', 'infrastructures', '["flux","fluxcd","flux cd","gitops flux"]'),
('Istio', 'infrastructures', '["istio","service mesh istio"]'),
('Linkerd', 'infrastructures', '["linkerd","service mesh linkerd"]'),
('Envoy', 'infrastructures', '["envoy","envoy proxy"]'),
('Nginx', 'infrastructures', '["nginx","エンジンエックス","Nginx"]'),
('Apache HTTP', 'infrastructures', '["apache http","apache httpd","httpd"]'),
('HAProxy', 'infrastructures', '["haproxy","ha proxy","load balancer"]'),
('Caddy', 'infrastructures', '["caddy","caddy server"]'),
('Vault', 'infrastructures', '["vault","hashicorp vault","secrets management"]'),
('Consul', 'infrastructures', '["consul","hashicorp consul","service discovery"]'),
('Nomad', 'infrastructures', '["nomad","hashicorp nomad"]'),
('Packer', 'infrastructures', '["packer","hashicorp packer","image build"]'),
('Vagrant', 'infrastructures', '["vagrant","hashicorp vagrant"]'),
('Ansible', 'infrastructures', '["ansible","アンシブル","ansible playbook"]'),
('Chef', 'infrastructures', '["chef","chef infra","chef cookbook"]'),
('Puppet', 'infrastructures', '["puppet","puppet manifest","puppet labs"]'),
('SaltStack', 'infrastructures', '["saltstack","salt","salt-stack"]'),
('CloudFormation', 'infrastructures', '["cloudformation","cfn","aws cfn"]'),
('Pulumi', 'infrastructures', '["pulumi","pulumi iac"]'),
('Serverless Framework', 'infrastructures', '["serverless","serverless framework","sls"]'),
('OpenTofu', 'infrastructures', '["opentofu","open tofu","tofu"]'),
('Prometheus', 'infrastructures', '["prometheus","prometheus monitoring"]'),
('Grafana', 'infrastructures', '["grafana","grafana monitoring"]'),
('Loki', 'infrastructures', '["loki","grafana loki","log aggregation"]'),
('Jaeger', 'infrastructures', '["jaeger","distributed tracing jaeger"]'),
('Zipkin', 'infrastructures', '["zipkin","distributed tracing"]'),
('OpenTelemetry', 'infrastructures', '["otel","opentelemetry","open telemetry"]'),
('Datadog', 'infrastructures', '["datadog","data dog","dd"]'),
('New Relic', 'infrastructures', '["newrelic","new relic","NR"]'),
('Dynatrace', 'infrastructures', '["dynatrace","dyna trace"]'),
('PagerDuty', 'infrastructures', '["pagerduty","pager duty"]'),
('OpsGenie', 'infrastructures', '["opsgenie","ops genie"]'),
('Sentry', 'infrastructures', '["sentry","sentry.io","エラー監視"]'),
('Fluentd', 'infrastructures', '["fluentd","fluentbit","fluent bit"]'),
('Logstash', 'infrastructures', '["logstash","elk logstash"]'),

-- ===== tools (ツール) 追加 ~60件 =====
('GitHub', 'tools', '["github","git hub","ギットハブ"]'),
('GitLab', 'tools', '["gitlab","git lab","ギットラブ"]'),
('Bitbucket', 'tools', '["bitbucket","bit bucket"]'),
('GitHub Actions', 'tools', '["github actions","gha","github ci"]'),
('GitLab CI', 'tools', '["gitlab ci","gitlab ci/cd","gitlab pipeline"]'),
('CircleCI', 'tools', '["circleci","circle ci"]'),
('Jenkins', 'tools', '["jenkins","ジェンキンス"]'),
('Travis CI', 'tools', '["travis","travis ci","travis-ci"]'),
('TeamCity', 'tools', '["teamcity","team city","jetbrains ci"]'),
('Bamboo', 'tools', '["bamboo","atlassian bamboo"]'),
('Jira', 'tools', '["jira","ジラ","atlassian jira"]'),
('Confluence', 'tools', '["confluence","コンフルエンス","atlassian confluence"]'),
('Notion', 'tools', '["notion","ノーション"]'),
('Slack', 'tools', '["slack","スラック"]'),
('Microsoft Teams', 'tools', '["teams","microsoft teams","ms teams"]'),
('Backlog', 'tools', '["backlog","バックログ","nulab backlog"]'),
('Redmine', 'tools', '["redmine","レッドマイン"]'),
('Linear', 'tools', '["linear","linear.app"]'),
('Asana', 'tools', '["asana","アサナ"]'),
('Trello', 'tools', '["trello","トレロ"]'),
('Monday.com', 'tools', '["monday","monday.com"]'),
('Figma', 'tools', '["figma","フィグマ"]'),
('Sketch', 'tools', '["sketch","sketch app"]'),
('Adobe XD', 'tools', '["xd","adobe xd"]'),
('InVision', 'tools', '["invision","in vision"]'),
('Zeplin', 'tools', '["zeplin","ゼプリン"]'),
('Storybook', 'tools', '["storybook","story book","コンポーネントカタログ"]'),
('Postman', 'tools', '["postman","ポストマン"]'),
('Insomnia', 'tools', '["insomnia","insomnia rest"]'),
('Swagger', 'tools', '["swagger","swagger ui","openapi swagger"]'),
('OpenAPI', 'tools', '["openapi","open api","api specification"]'),
('SonarQube', 'tools', '["sonarqube","sonar qube","code quality"]'),
('ESLint', 'tools', '["eslint","es lint","javascript lint"]'),
('Prettier', 'tools', '["prettier","code formatter"]'),
('Husky', 'tools', '["husky","git hooks","pre-commit"]'),
('Webpack', 'tools', '["webpack","web pack","バンドラー"]'),
('Vite', 'tools', '["vite","vite.js","ヴィート"]'),
('Rollup', 'tools', '["rollup","rollup.js"]'),
('esbuild', 'tools', '["esbuild","es build"]'),
('Turbopack', 'tools', '["turbopack","turbo pack"]'),
('Nx', 'tools', '["nx","nrwl nx","monorepo nx"]'),
('Turborepo', 'tools', '["turborepo","turbo repo","vercel turborepo"]'),
('Lerna', 'tools', '["lerna","monorepo lerna"]'),
('pnpm', 'tools', '["pnpm","p npm","performant npm"]'),
('Bun', 'tools', '["bun","bun runtime","bun.sh"]'),
('Deno', 'tools', '["deno","deno runtime"]'),
('VS Code', 'tools', '["vscode","visual studio code","vs code"]'),
('IntelliJ IDEA', 'tools', '["intellij","intellij idea","jetbrains intellij"]'),
('Eclipse', 'tools', '["eclipse","eclipse ide"]'),
('PyCharm', 'tools', '["pycharm","jetbrains pycharm"]'),
('WebStorm', 'tools', '["webstorm","jetbrains webstorm"]'),
('Xcode', 'tools', '["xcode","apple xcode"]'),
('Android Studio', 'tools', '["android studio","androidstudio"]'),
('Tableau', 'tools', '["tableau","タブロー","tableau desktop"]'),
('Power BI', 'tools', '["powerbi","power bi","microsoft power bi"]'),
('Looker', 'tools', '["looker","looker studio","google looker"]'),
('Metabase', 'tools', '["metabase","メタベース"]'),
('Redash', 'tools', '["redash","re:dash"]'),
('Apache Superset', 'tools', '["superset","apache superset"]'),
('draw.io', 'tools', '["drawio","draw.io","diagrams.net"]'),
('Lucidchart', 'tools', '["lucidchart","lucid chart"]'),
('Miro', 'tools', '["miro","ミロ","online whiteboard"]'),

-- ===== methodologies (手法) 追加 ~20件 =====
('DevOps', 'methodologies', '["devops","dev ops","DevOps文化"]'),
('SRE', 'methodologies', '["sre","site reliability engineering","サイトリライアビリティ"]'),
('GitOps', 'methodologies', '["gitops","git ops"]'),
('BDD', 'methodologies', '["bdd","behavior driven development","振る舞い駆動開発"]'),
('TDD', 'methodologies', '["tdd","test driven development","テスト駆動開発"]'),
('DDD', 'methodologies', '["ddd","domain driven design","ドメイン駆動設計"]'),
('CQRS', 'methodologies', '["cqrs","command query responsibility segregation"]'),
('Event Sourcing', 'methodologies', '["event sourcing","イベントソーシング"]'),
('マイクロサービス', 'methodologies', '["microservices","マイクロサービスアーキテクチャ","micro services"]'),
('モノリス', 'methodologies', '["monolith","monolithic","モノリシック"]'),
('Clean Architecture', 'methodologies', '["clean architecture","クリーンアーキテクチャ","CA"]'),
('ヘキサゴナルアーキテクチャ', 'methodologies', '["hexagonal architecture","ports and adapters","ヘキサゴナル"]'),
('CI/CD', 'methodologies', '["cicd","ci cd","継続的インテグレーション","継続的デリバリー"]'),
('コードレビュー', 'methodologies', '["code review","レビュー","PR review"]'),
('ペアプログラミング', 'methodologies', '["pair programming","ペアプロ"]'),
('モブプログラミング', 'methodologies', '["mob programming","モブプロ"]'),
('リファクタリング', 'methodologies', '["refactoring","リファクタ"]'),
('オブジェクト指向', 'methodologies', '["oop","object oriented","オブジェクト指向設計","OOP"]'),
('関数型プログラミング', 'methodologies', '["functional programming","FP","関数型"]'),
('REST API', 'methodologies', '["rest","restful","rest api","RESTful API"]'),

-- ===== dwh (DWH/BI) 追加 ~15件 =====
('Snowflake', 'dwh', '["snowflake","スノーフレーク","snowflake dwh"]'),
('Google BigQuery', 'dwh', '["bq","bigquery dwh","big query"]'),
('Amazon Redshift', 'dwh', '["redshift","amazon redshift dwh"]'),
('Azure Synapse', 'dwh', '["synapse","azure synapse analytics"]'),
('dbt', 'dwh', '["dbt","data build tool","dbt cloud","dbt core"]'),
('Databricks', 'dwh', '["databricks","data bricks","apache delta"]'),
('Fivetran', 'dwh', '["fivetran","fivetran etl"]'),
('Airbyte', 'dwh', '["airbyte","air byte"]'),
('Stitch', 'dwh', '["stitch","stitch data","talend stitch"]'),
('Apache Hive', 'dwh', '["hive","apache hive","hiveql"]'),
('Presto', 'dwh', '["presto","prestodb","prestoSQL","trino"]'),
('Apache Druid', 'dwh', '["druid","apache druid"]'),
('ClickHouse', 'dwh', '["clickhouse","click house"]'),
('Metriql', 'dwh', '["metriql","headless bi"]'),
('Lightdash', 'dwh', '["lightdash","light dash"]'),

-- ===== os (OS) 追加 ~10件 =====
('Ubuntu', 'os', '["ubuntu","ウブンツ","ubuntu linux"]'),
('CentOS', 'os', '["centos","cent os","redhat clone"]'),
('Rocky Linux', 'os', '["rocky","rocky linux","rhel clone"]'),
('AlmaLinux', 'os', '["almalinux","alma linux"]'),
('Red Hat Enterprise Linux', 'os', '["rhel","red hat","redhat linux","RHEL"]'),
('Amazon Linux', 'os', '["amazon linux","amzn linux","al2","al2023"]'),
('Debian', 'os', '["debian","デビアン"]'),
('Alpine Linux', 'os', '["alpine","alpine linux","alpine docker"]'),
('FreeBSD', 'os', '["freebsd","bsd","free bsd"]'),
('macOS', 'os', '["macos","mac os","osx","mac"]'),

-- ===== design (デザイン) 追加 ~20件 =====
('UI設計', 'design', '["ui設計","ui design","ユーザーインターフェース設計"]'),
('UX設計', 'design', '["ux設計","ux design","ユーザーエクスペリエンス設計"]'),
('プロトタイピング', 'design', '["prototyping","プロトタイプ","prototype"]'),
('ワイヤーフレーム', 'design', '["wireframe","ワイヤフレーム","画面設計"]'),
('Adobe Photoshop', 'design', '["photoshop","ps","フォトショ","フォトショップ"]'),
('Adobe Illustrator', 'design', '["illustrator","ai","イラストレーター","イラレ"]'),
('Adobe After Effects', 'design', '["after effects","ae","アフターエフェクツ"]'),
('Adobe Premiere', 'design', '["premiere","premiere pro","プレミア","映像編集"]'),
('Canva', 'design', '["canva","キャンバ"]'),
('Unity', 'design', '["unity","unity3d","ユニティ","ゲームエンジン"]'),
('Unreal Engine', 'design', '["unreal","ue5","ue4","アンリアルエンジン"]'),
('Blender', 'design', '["blender","ブレンダー","3DCG"]'),
('Cinema 4D', 'design', '["cinema4d","c4d","cinema 4d"]'),
('Maya', 'design', '["maya","autodesk maya","3dmax"]'),
('アクセシビリティ', 'design', '["accessibility","a11y","wcag","アクセシビリティ対応"]'),
('デザインシステム', 'design', '["design system","デザインシステム","コンポーネントライブラリ"]'),
('レスポンシブデザイン', 'design', '["responsive design","レスポンシブ","スマホ対応"]'),

-- ===== marketing (マーケティング) 追加 ~15件 =====
('SEO', 'marketing', '["seo","検索エンジン最適化","search engine optimization"]'),
('SEM', 'marketing', '["sem","search engine marketing","リスティング"]'),
('Google Analytics', 'marketing', '["ga","ga4","google analytics 4","アナリティクス"]'),
('Google Tag Manager', 'marketing', '["gtm","google tag manager","タグマネージャー"]'),
('MA', 'marketing', '["ma","marketing automation","マーケティングオートメーション"]'),
('Salesforce Marketing Cloud', 'marketing', '["sfmc","marketing cloud","セールスフォースMA"]'),
('HubSpot', 'marketing', '["hubspot","ハブスポット"]'),
('Marketo', 'marketing', '["marketo","マルケト"]'),
('SNS運用', 'marketing', '["sns","twitter","instagram","x運用","sns marketing"]'),
('コンテンツマーケティング', 'marketing', '["content marketing","コンテンツ","SEO記事"]'),
('A/Bテスト', 'marketing', '["ab test","a/bテスト","split test","実験"]'),
('CRM', 'marketing', '["crm","customer relationship management","顧客管理"]'),
('CDP', 'marketing', '["cdp","customer data platform","顧客データ基盤"]'),
('広告運用', 'marketing', '["広告","google ads","meta ads","programmatic","DSP","SSP"]'),

-- ===== others (その他) 追加 ~20件 =====
('生成AI', 'others', '["generative ai","genai","生成系AI","LLM活用"]'),
('RAG', 'others', '["rag","retrieval augmented generation","検索拡張生成"]'),
('プロンプトエンジニアリング', 'others', '["prompt engineering","プロンプト設計","プロンプトチューニング"]'),
('ファインチューニング', 'others', '["fine tuning","finetuning","モデル微調整"]'),
('MLOps', 'others', '["mlops","ml ops","機械学習運用"]'),
('DataOps', 'others', '["dataops","data ops"]'),
('フィンテック', 'others', '["fintech","fintec","金融テック"]'),
('ブロックチェーン', 'others', '["blockchain","block chain","分散台帳"]'),
('Web3', 'others', '["web3","web 3.0","dapps","分散アプリ"]'),
('IoT', 'others', '["iot","internet of things","モノのインターネット"]'),
('エッジコンピューティング', 'others', '["edge computing","エッジ","edge"]'),
('組み込み開発', 'others', '["embedded","組込み","エンベデッド","RTOS"]'),
('FPGA', 'others', '["fpga","field programmable gate array"]'),
('アジャイル', 'others', '["agile","アジャイル開発","スクラム開発"]'),
('ウォーターフォール', 'others', '["waterfall","ウォーターフォール開発"]'),
('PMO', 'others', '["pmo","project management office","プロジェクト管理"]'),
('IT戦略', 'others', '["it戦略","it strategy","DX戦略","デジタル戦略"]'),
('要件定義', 'others', '["要件定義","requirements definition","要求分析"]'),
('基本設計', 'others', '["基本設計","外部設計","high level design"]'),
('詳細設計', 'others', '["詳細設計","内部設計","low level design"]'),
('システム移行', 'others', '["マイグレーション","migration","system migration","データ移行"]'),
('セキュリティ診断', 'others', '["脆弱性診断","pentest","ペネトレーションテスト","セキュリティテスト"]'),
('ゼロトラスト', 'others', '["zero trust","ゼロトラストセキュリティ"]'),
('ID管理', 'others', '["idm","id管理","identity management","iam","sso","ldap"]')

ON CONFLICT (name) DO NOTHING;
